#+title:  Lección 3
#+author: Marcos Bujosa
#+STARTUP: show4levels
#+LANGUAGE: es-es

#+EXPORT_FILE_NAME: pub/Lecc03

# +OPTIONS: toc:nil
#+OPTIONS: tags:nil

#+LATEX_CLASS: article

#+LATEX_HEADER: \usepackage[spanish]{babel}
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+LaTeX_HEADER: \usepackage[svgnames,x11names]{xcolor}
#+LaTeX_HEADER: \hypersetup{linktoc = all, colorlinks = true, urlcolor = DodgerBlue4, citecolor = PaleGreen1, linkcolor = SpringGreen4}
#+LaTeX_HEADER: \PassOptionsToPackage{hyphens}{url}
# +LaTeX_HEADER: \input{notacionLinAlg.tex}
#+LaTeX_HEADER: \usepackage{nacal}

#+LaTeX_HEADER: \usepackage{framed}

#+LaTeX_HEADER: \usepackage{listings}
#+LaTeX_HEADER: \input{hansl.tex}
#+LaTeX_HEADER: \lstnewenvironment{hansl-gretl}
#+LaTeX_HEADER: {\lstset{language={hansl},basicstyle={\ttfamily\footnotesize},numbers,rame=single,breaklines=true}}
#+LaTeX_HEADER: {}
#+LaTeX_HEADER: \newcommand{\hansl}[1]{\lstset{language={hansl},basicstyle={\ttfamily\small}}\lstinline{#1}}
# +LaTeX_HEADER: \lstset{backgroundcolor=\color{white},basicstyle=\ttfamily\footnotesize,breaklines=true, captionpos=b,commentstyle=\color{mygreen},escapeinside={\%*}{*)}, keywordstyle=\color{blue},stringstyle=\color{mymauve}, }
# +LaTeX_HEADER: \lstset{backgroundcolor=\color{lightgray!20},basicstyle=\ttfamily\footnotesize,breaklines=true, }
#+LaTeX_HEADER: \lstset{backgroundcolor=\color{lightgray!20}, }

#+name: setup-listings
#+begin_src emacs-lisp :exports none :results silent
  (setq org-latex-listings 'listings)
  (setq org-latex-custom-lang-environments
  	;'((emacs-lisp "common-lispcode")))
  	'((emacs-lisp "hansl-gretl")))
  (setq org-latex-listings-options
	'(("frame" "lines")
	  ("basicstyle" "\\scriptsize")
	  ("basicstyle" "\\ttfamily")
	  ("numbers=none" "left")
	  ("backgroundcolor=\\color{lightgray!20}")
	  ("numberstyle" "\\tiny")))
  (setq org-latex-to-pdf-process
	'("pdflatex -interaction nonstopmode -output-directory %o %f"
	"pdflatex -interaction nonstopmode -output-directory %o %f"
	"pdflatex -interaction nonstopmode -output-directory %o %f"))
  (org-add-link-type
   "latex" nil
   (lambda (path desc format)
     (cond
      ((eq format 'html)
       (format "<span class=\"%s\">%s</span>" path desc))
      ((eq format 'latex)
       (format "\\%s{%s}" path desc)))))
#+end_src

# \lstnewenvironment{code}
#     {\lstset{language=haskell,
#     basicstyle=\small\ttfamily,
#     numbers=left,
#     numberstyle=\tiny\color{gray},
#     backgroundcolor=\color{lightgray},
#     firstnumber=auto
#     }}
#     {}

#+bibliography: ref.bib

# +latex: \clearpage

#+LATEX: \clearpage

* Datos de Anscombe
   :PROPERTIES:
   :header-args: :tangle ./pub/scripts/anscombe.inp
   :END:

| Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/anscombe.inp][anscombe.inp]] |

En esta práctica con [[https://gretl.sourceforge.net/es.html][Gretl]] trabajaremos con los [[http://en.wikipedia.org/wiki/Anscombe's_quartet][datos]] diseñados por
F.J. Anscombe para ilustrar la importancia de /ver/ los diagramas de
dispersión entre distintas variables antes de realizar ninguna
regresión y así identificar deficiencias en el planteamiento de los
modelo, pues si únicamente se analizan los resultados numéricos de las
estimaciones dichas deficiencias quedan ocultas.

** La importancia de /ver/ los datos
**** Objetivo
Cuando se ajusta un modelo a los datos, es NECESARIO comenzar
observando gráficamente los datos. F.J. Anscombe diseñó este
[[http://en.wikipedia.org/wiki/Anscombe's_quartet][conjunto de datos]]
para ilustrar la importancia de representar gráficamente los datos
antes de realizar un análisis empírico.

** Los datos

| \Vect[1]{y} | \Vect[2]{y} | \Vect[3]{y} | \Vect[4]{y} | \Vect{x} | \Vect[4]{x} |
|-------------+-------------+-------------+-------------+----------+-------------|
|        8.04 |        9.14 |        7.46 |        6.58 |       10 |           8 |
|        6.95 |        8.14 |        6.77 |        5.76 |        8 |           8 |
|        7.58 |        8.74 |       12.74 |        7.71 |       13 |           8 |
|        8.81 |        8.77 |        7.11 |        8.84 |        9 |           8 |
|        8.33 |        9.26 |        7.81 |        8.47 |       11 |           8 |
|        9.96 |        8.10 |        8.84 |        7.04 |       14 |           8 |
|        7.24 |        6.13 |        6.08 |        5.25 |        6 |           8 |
|        4.26 |        3.10 |        5.39 |       12.50 |        4 |          19 |
|       10.84 |        9.13 |        8.15 |        5.56 |       12 |           8 |
|        4.82 |        7.26 |        6.42 |        7.91 |        7 |           8 |
|        5.68 |        4.74 |        5.73 |        6.89 |        5 |           8 |
|-------------+-------------+-------------+-------------+----------+-------------|

** Los estadísticos de los datos


|------------------------------------------------------------------------+-------|
| Estadísticos de los datos                                              |       |
|------------------------------------------------------------------------+-------|
| Media de cada una de las variables \Vect{x}:                           |   9.0 |
| Varianza de cada una de las variables \Vect{x}:                        |  11.0 |
| Media de cada una de las variables \Vect{y}:                           |   7.5 |
| Varianza de cada una de las variables \Vect{y}:                        |  4.12 |
| Correlación entre las variables \Vect{x} e \Vect{y} de cada regresión: | 0.816 |
|------------------------------------------------------------------------+-------|

|--------------------------------------------------------+------|
| Rectas de regresión                                    |  R^2 |
|--------------------------------------------------------+------|
| $\VEstmc[1]{y} = 3\cdot\Vect{1} + 0.5\cdot\Vect{x}$    | 0.67 |
| $\VEstmc[2]{y} = 3\cdot\Vect{1} + 0.5\cdot\Vect{x}$    | 0.67 |
| $\VEstmc[3]{y} = 3\cdot\Vect{1} + 0.5\cdot\Vect{x}$    | 0.67 |
| $\VEstmc[4]{y} = 3\cdot\Vect{1} + 0.5\cdot\Vect[4]{x}$ | 0.67 |
|--------------------------------------------------------+------|

** Actividad 1 - Estadísticos descriptivos

***** Carga de datos
*/~Archivo --> Abrir datos --> Archivo de muestra~/* y en la pestaña
*/~Gretl~/* seleccione =anscombe=.

#+latex: {\vspace{3pt} \color{gray!70!black}
/o bien teclee en linea de comandos/:
  #+NAME: DA-carga-datos
  #+begin_src hansl
open anscombe
  #+end_src  
#+latex: }

#+BEAMER:  \vspace{-8pt}

***** Visualice los estadísticos descriptivos de las datos

- Marque una variable (o varias) y ``Pinche'' con el botón derecho.
  Elija */~Estadísticos principales~/*
  
  #+latex: {\vspace{3pt} \color{gray!70!black}
  /o bien teclee en linea de comandos/ =summary= seguido de las series. Por ejemplo:
    #+NAME: DA-estadisticos-simples
    #+begin_src hansl
summary --simple y1 y2 y3 y4 x x4
    #+end_src
  #+latex: }

#+BEAMER:  \vspace{-8pt}
  
***** Observar la correlación entre variables
  
- */~Ver --> Matriz de correlación~/* y elija variables

  #+latex: {\vspace{3pt} \color{gray!70!black}
  /o, por ejemplo, teclee en linea de comandos/:
    #+NAME: DA-correlaciones
    #+begin_src hansl
corr y1 y2 y3 y4 x x4
    #+end_src
  #+latex: }

** Actividad 2 - Cuatro regresiones

Realice los siguientes cuatro ajustes MCO
- Modelo 1: $\quad \VEstmc[1]{y} = \Estmc{a}\Vect{1} + \Estmc{b}\Vect{x}$ 
- Modelo 2: $\quad \VEstmc[2]{y} = \Estmc{a}\Vect{1} + \Estmc{b}\Vect{x}$ 
- Modelo 3: $\quad \VEstmc[3]{y} = \Estmc{a}\Vect{1} + \Estmc{b}\Vect{x}$ 
- Modelo 4: $\quad \VEstmc[4]{y} = \Estmc{a}\Vect{1} + \Estmc{b}\Vect[4]{x}$
   
y compare los resultados.

- Para cada modelo:

  */~Modelo -> Mínimos Cuadrados Ordinarios~/*; indique regresando y
  regresores. Pulse */~Aceptar~/* (guarde el modelo como icono).
  
  #+latex: {\vspace{3pt} \color{gray!70!black}
  /o bien teclee en linea de comandos/:
    #+NAME: DA-regresiones
    #+begin_src hansl
Modelo1 <- ols y1 0 x
Modelo2 <- ols y2 0 x
Modelo3 <- ols y3 0 x
Modelo4 <- ols y4 0 x4
    #+end_src
  #+latex: }
      
** Actividad 3 - Discusión

***** Compare los estadísticos de los distintos modelos
- el coeficiente de determinación y en el coeficiente de determinación ajustado 
- la suma de cuadrados de los residuos,
- la desviación típica de los errores de ajuste (~D.T. de la regresión~),
- los estadísticos \testadistico
- los p-valores.

***** A la luz de los estadísticos de las cuatro regresiones ¿Qué modelo es mejor?
      
***** Observe el diagrama de dispersión XY en cada modelo

  - ``pinche'' en */~Ver --> Gráficos --> Gráfico XY (scatter)~/*
    Elija la variable para el eje X (regresor) y la variable Y
    (regresando)

  #+latex: {\vspace{3pt} \color{gray!70!black}
  /o, por ejemplo, teclee en linea de comandos/:
    #+begin_src hansl
gnuplot y1 x
    #+end_src
  /podemos pintar varios diagramas juntos con/:
    #+begin_src hansl
gnuplot y1 y2 y3 x
    #+end_src
  /o varios diagramas separados con/:
    #+NAME: DA-diagramas
    #+begin_src hansl
scatters y1 y2 y3 ; x
scatters y4 ; x4
    #+end_src    
  #+latex: }

    \vspace{-10pt}
  
***** De los cuatro modelos\dots ¿cuáles parecen razonables?


# +LATEX: \clearpage
#+latex: \vspace{16pt}
#+latex: \noindent
*Código completo de la práctica* ~anscombe.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/anscombe.inp}
#+LATEX: \clearpage

** COMMENT Resultado en Gretl

#+begin_src bash :results file :file anscombeOUTPUT.txt :output-dir ~/gretl/resultados 
  gretlcli -b pub/anscombe.inp 
#+end_src

#+RESULTS:
[[file:~/gretl/resultados/anscombeOUTPUT.txt]]



* Los errores de ajuste MCO son perpendiculares a los regresores
   :PROPERTIES:
   :header-args: :tangle ./pub/scripts/TextilTheil.inp
   :END:

| Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/TextilTheil.inp][TextilTheil.inp]] |

***** Carga de datos

Vamos a usar el conjunto de datos de consumo percápita de textiles, de
Henri Theil, Principios de Econometría, Nueva York: Wiley, 1971,
p. 102.  El conjunto de datos consta de 17 observaciones anuales de
series de tiempo para el periodo 1923--1939 del consumo de textiles en
los Países Bajos. Todas las variables son expresadas como índices con
base 100 en 1925.

*/~Archivo --> Abrir datos --> Archivo de muestra~/* y en la pestaña
*/~Gretl~/* seleccione =theil=.

#+latex: {\vspace{3pt} \color{gray!70!black}
/o bien teclee en linea de comandos/:
  #+begin_src hansl
  open theil
  #+end_src  
#+latex: }

***** Ajuste por MCO el modelo
\begin{displaymath}
  \Vect{y}=\Estmc{\beta_1}\Vect{1}+\Estmc{\beta_2}\Vect[2]{X}+\Estmc{\beta_3}\Vect[3]{X}+\res
\end{displaymath}
donde \Vect{y} es el consumo de textiles \Vect[2]{X} la renta y
\Vect[3]{X} los precios relativos: */~Modelo -> Mínimos Cuadrados
Ordinarios~/*; indique ~consume~ como regresando y ~const~, ~income~ y
~relprice~ como regresores. Pulse */~Aceptar~/* (guarde el modelo como
icono).

#+latex: {\vspace{3pt} \color{gray!70!black}
/o bien teclee en linea de comandos/:
  #+begin_src hansl
  AjusteMCO <- ols consume const income relprice
  #+end_src  
#+latex: }

***** Guardado de datos ajustados y de los errores

En la ventana del modelo ajustado: */~Guardar -> Valores estimados~/*
e indique un nombre, por ejemplo ~yhat~. Lo mismo para los errores:
*/~Guardar -> Residuos~/* y como nombre por ejemplo ~ehat~

#+latex: {\vspace{3pt} \color{gray!70!black}
/o bien teclee en linea de comandos/:
  #+begin_src hansl
  series ehat = $uhat
  series yhat = $yhat
  #+end_src  
#+latex: }

***** Verificación de que los residuos son ortogonales a los regresores y al ajuste, pero no al regresando

Compruebe que
\begin{displaymath}
  \media{\res}=0,\quad
  \mediap*{\prodH{\res}{\Vect[2]{x}}}=0,\quad
  \mediap*{\prodH{\res}{\Vect[3]{x}}}=0,\quad
  \mediap*{\prodH{\res}{\VEstmc{y}}} =0\quad\text{pero}\quad
  \mediap*{\prodH{\res}{\Vect{y}}}\ne0.
\end{displaymath}

- En la ventana principal: */~Añadir -> Definir nueva variable~/* y en
  cada caso escribir la formula y pulsar en */~Aceptar~/*
  1) ei = ehat*income
  2) er = ehat*relprice
  3) ey = ehat*yhat
  4) ec = ehat*consume

#+latex: {\vspace{3pt} \color{gray!70!black}
/o bien teclee en linea de comandos/:
  #+begin_src hansl
  series ei = ehat*income
  series er = ehat*relprice
  series ey = ehat*yhat
  series ec = ehat*consume
  #+end_src  
#+latex: }

- Observe los valores medios de los productos, es decir, de ~ehat~,
  ~ei~, ~er~, ~ey~ y ~ec~ marcando las variables haciendo click sobre
  ellas con el botón derecho y eligiendo */~Estadísticos
  principales~/*

#+latex: {\vspace{3pt} \color{gray!70!black}
/o bien teclee en linea de comandos/:
  #+begin_src hansl
  summary --simple ehat ei er ey ec
  #+end_src  
#+latex: }

***** Explique los resultados.


# +LATEX: \clearpage
#+latex: \vspace{16pt}
#+latex: \noindent
*Código completo de la práctica* ~TextilTheil.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/TextilTheil.inp}
#+LATEX: \clearpage


* El coeficiente de determinación como cuadrado de la correlación entre valores observados y ajustados
   :PROPERTIES:
   :header-args: :tangle ./pub/scripts/EjPviviendaR2.inp
   :END:

| Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/EjPviviendaR2.inp][EjPviviendaR2.inp]] |

Calcule el coeficiente de determinación $R^2$ para el ejemplo del
precio de las viviendas, pero empleando el coeficiente de correlación
entre los precios y los precios ajustados.  (\textbf{Pista:} calcule
el coeficiente de correlación lineal simple entre \VEstmc{Y} y
\Vect{Y} y elévelo al cuadrado.) Puede hacerlo mediante los menús
desplegables de las ventanas de Gretl, /o bien en linea de comandos/:

#+latex: \vspace{16pt}
#+latex: {\vspace{3pt} \color{gray!70!black}
#+begin_src hansl :exports none
open data3-1
ols price const sqft
genr phat  = $yhat
scalar Coef_detR2 = corr(price,phat)^2
#+end_src
#+latex: }

\lstinputlisting{scripts/EjPviviendaR2.inp}

#+LATEX: \clearpage


* La importancia a los criterios de ajuste es muy relativa
   :PROPERTIES:
   :header-args: :tangle ./pub/scripts/PesoEdad.inp
   :END:

   | Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/PesoEdad.inp][PesoEdad.inp]] |

   - Cargue los datos del ejemplo del peso y edad de ocho niños.
         
     - Puede descargar el fichero =PesoEdad.gdt= del subdirectorio
       =datos= del directorio con el material del curso,
   
     - o introducir los datos manualmente siguiendo */~Archivo ->
       Nuevo conjunto de datos~/*. Indique que hay 8 observaciones de
       sección cruzada, y marque ``empezar a introducir los valores de
       los datos''. Introduzca el nombre de la primera variable y
       luego los datos del peso de cada niño. Pulsando en ~+~ puede
       añadir la segunda variable.
       
   -  Genere la serie de edades al cuadrado y de la de edades al cubo.
   
   -  Ajuste el modelo
     $\VEstmc{peso}=\Estmc{\beta_1}\Vect{1}+\Estmc{\beta_2}\Vect{edad}$
     y añádalo a la tabla de modelos.
   
   
      - Guarde el modelo como icono y pulse sobre su icono con el
        botón derecho. Seleccione */~Añadir a la tabla de modelos~/*
	
         - o bien, tras estimar el modelo teclee ~modeltab add~
   	
   - Ajuste
     $\VEstmc{peso}=\Estmc{\beta_1}\Vect{1}+\Estmc{\beta_2}\Vect{edad}+\Estmc{\beta_3}\Vect[][2]{(edad)}$
     y añádalo a la tabla de modelos.
      
   - Ajuste
     $\VEstmc{peso}=\Estmc{\beta_1}\Vect{1}+\Estmc{\beta_2}\Vect{edad}+\Estmc{\beta_3}\Vect[][2]{(edad)}+\Estmc{\beta_3}\Vect[][3]{(edad)}$
     y añádalo a la tabla de modelos.
        
   - Compare los ajustes: pinchando sobre el icono de =Tabla de
     modelos=; o bien tecleando ~modeltab show~.

   - Genere las figuras de los distintos ajustes.

Fíjese que que en los dos últimos ajustes las potencias de la edad son
regresores, pero que en los tres modelos la única variable
/explicativa/ del peso es la edad (variable explicativa y regresor no
son sinónimos).

El siguiente guión realiza todos los pasos
#+latex: {\vspace{3pt} \color{gray!70!black}
#+begin_src hansl :exports none
open datos/PesoEdad.gdt

series Edad2=Edad^2
series Edad3=Edad^3

Modelo1 <- ols Peso_Kg const Edad
modeltab add
Modelo2 <- ols Peso_Kg const Edad Edad2
modeltab add
Modelo3 <- ols Peso_Kg const Edad Edad2 Edad3
modeltab add
modeltab show   

series yhat1=Modelo1.$yhat
Modelo1 <- gnuplot Peso_Kg yhat1 Edad --with-lp=yhat1 --output="display"
series yhat2=Modelo2.$yhat
Modelo2 <- gnuplot Peso_Kg yhat2 Edad --with-lp=yhat2 --output="display" --fit=quadratic
series yhat3=Modelo3.$yhat
Modelo3 <- gnuplot Peso_Kg yhat3 Edad --with-lp=yhat3 --output="display" --fit=cubic   
#+end_src
#+latex: }

#+LATEX: \vspace{12pt}
\lstinputlisting{scripts/PesoEdad.inp}


#+LATEX: \clearpage


* ¿Tiene sentido llamar variable explicativa a cualquier regresor?
   :PROPERTIES:
   :header-args: :tangle ./pub/scripts/cigfecfr.inp
   :END:

   | Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/cigfecfr.inp][cigfecfr.inp]] |
   
   /*Una regresión infantil:* exploremos la teoría que ``Dumbo''
      ofrece a los niños sobre la natalidad y las cigüeñas./
   
   ¿Podemos encontrar relación entre la tasa de fecundidad de las
   mujeres francesas (=fec=) y la densidad de cigüeñas (=cig=) en
   Alsacia para el período 1945-1986 (=annee=)? La tasa de fecundidad
   está calculada como número de niños por 10000 mujeres (Indicateur
   conjucturel de fécondité en 2004 par l'INSEE http://www.insee.fr).
   Las cifras de cigüeñas proceden de The Global Population Database:
   NERC Centre for Population Biology
   (\url{http://www3.imperial.ac.uk/cpb/research/patternsandprocesses/gpdd})
   y se trata del número de parejas de cigüeñas que anidan en la
   región de Alsacia.

   - Cargue el conjunto de datos ~cigfecfr.inp~.
     
   - Realice un diagrama de dispersión entre =fec= y =cig= y calcule
     el coeficiente de correlación.

   - Ajuste por MCO la tasa de fecundidad =fec= con la constante y =cig=

   - Realice un gráfico de series temporales de ambas
     variables. Observe que parece haber un retardo entre la aparición
     de las cigüeñas y la variación en la tasa de natalidad.

   - Cree una nueva serie =cig6= que sea la serie =cig= retardada 6
     meses y repita los pasos anteriores. Observe que el ajuste
     mejora.

   - A la luz de los resultados ¿``explica'' el número de parejas de
     cigüeñas casi el 90% de la variabilidad en la natalidad de la
     región de Alsacia en esos años?

El siguiente guión realiza todos los pasos
#+latex: {\vspace{3pt} \color{gray!70!black}
#+begin_src hansl :exports none
open datos/cigfecfr.gdt

Diagrama  <- gnuplot fec cig  --output="display"
scalar rho = corr(fec, cig)
ols fec 0 cig

FecCig <- gnuplot fec cig --time-series --with-lines --output="display" 
series cig6=cig(-6)

Diagrama6 <- gnuplot fec cig6 --output="display"
scalar rho = corr(fec, cig6)
ols fec 0 cig6
#+end_src
#+latex: }

#+LATEX: \vspace{12pt}
\lstinputlisting{scripts/cigfecfr.inp}

     
