#+title:  Lección 2
#+author: Marcos Bujosa
#+STARTUP: show4levels
#+LANGUAGE: es-es

#+EXPORT_FILE_NAME: pub/Lecc02

# +OPTIONS: toc:nil
#+OPTIONS: tags:nil

#+LATEX_CLASS: article
#+LATEX_HEADER: \usepackage[spanish]{babel}
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+LaTeX_HEADER: \usepackage[svgnames,x11names]{xcolor}
#+LaTeX_HEADER: \hypersetup{linktoc = all, colorlinks = true, urlcolor = DodgerBlue4, citecolor = PaleGreen1, linkcolor = SpringGreen4}
#+LaTeX_HEADER: \PassOptionsToPackage{hyphens}{url}
# +LaTeX_HEADER: \input{notacionLinAlg.tex}
#+LaTeX_HEADER: \usepackage{nacal}

#+LaTeX_HEADER: \usepackage{framed}

#+LaTeX_HEADER: \usepackage{listings}
#+LaTeX_HEADER: \input{hansl.tex}
#+LaTeX_HEADER: \lstnewenvironment{hansl-gretl}
#+LaTeX_HEADER: {\lstset{language={hansl},basicstyle={\ttfamily\footnotesize},numbers,rame=single,breaklines=true}}
#+LaTeX_HEADER: {}
#+LaTeX_HEADER: \newcommand{\hansl}[1]{\lstset{language={hansl},basicstyle={\ttfamily\small}}\lstinline{#1}}
# +LaTeX_HEADER: \lstset{backgroundcolor=\color{white},basicstyle=\ttfamily\footnotesize,breaklines=true, captionpos=b,commentstyle=\color{mygreen},escapeinside={\%*}{*)}, keywordstyle=\color{blue},stringstyle=\color{mymauve}, }
# +LaTeX_HEADER: \lstset{backgroundcolor=\color{lightgray!20},basicstyle=\ttfamily\footnotesize,breaklines=true, }
#+LaTeX_HEADER: \lstset{backgroundcolor=\color{lightgray!20}, }

#+name: setup-listings
#+begin_src emacs-lisp :exports none :results silent
  (setq org-latex-listings 'listings)
  (setq org-latex-custom-lang-environments
  	;'((emacs-lisp "common-lispcode")))
  	'((emacs-lisp "hansl-gretl")))
  (setq org-latex-listings-options
	'(("frame" "lines")
	  ("basicstyle" "\\scriptsize")
	  ("basicstyle" "\\ttfamily")
	  ("numbers=none" "left")
	  ("backgroundcolor=\\color{lightgray!20}")
	  ("numberstyle" "\\tiny")))
  (setq org-latex-to-pdf-process
	'("pdflatex -interaction nonstopmode -output-directory %o %f"
	"pdflatex -interaction nonstopmode -output-directory %o %f"
	"pdflatex -interaction nonstopmode -output-directory %o %f"))
  (org-add-link-type
   "latex" nil
   (lambda (path desc format)
     (cond
      ((eq format 'html)
       (format "<span class=\"%s\">%s</span>" path desc))
      ((eq format 'latex)
       (format "\\%s{%s}" path desc)))))
#+end_src

# \lstnewenvironment{code}
#     {\lstset{language=haskell,
#     basicstyle=\small\ttfamily,
#     numbers=left,
#     numberstyle=\tiny\color{gray},
#     backgroundcolor=\color{lightgray},
#     firstnumber=auto
#     }}
#     {}

#+bibliography: ref.bib

#+latex: \clearpage

# Guión abreviado al que se accede en ocasiones desde los apuntes
#+begin_src hansl :noweb tangle :tangle ./pub/scripts/EjPvivienda2.inp :exports none
<<Lectura del fichero de datos>>
<<Guardamos scatterplot como icono>>
<<Ajuste MCO que se guarda como icono>>
<<Mostramos la ventana del ajuste MCO>>
<<Guardamos las series de valores ajustados y de errores>>
print -o price sqft phat ehat
#+end_src


* Precio de casas unifamiliares
   :PROPERTIES:
   :header-args: :tangle ./pub/scripts/EjPvivienda.inp
   :END:

| Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/EjPvivienda.inp][EjPvivienda.inp]] |
   
En esta primera práctica con [[https://gretl.sourceforge.net/es.html][Gretl]] reproduciremos el ejemplo visto
repetidamente en clase. Los datos corresponden a los precios de venta y
superficie útil de 14 casas unifamiliares en /University City/. San
Diego, California. Año 1990. [cite:@Ramanathan:IEA-02]

Veremos como mostrar los datos, generar diagramas de dispersión,
realizar un ajuste por MCO, y operar con series de datos y con
parámetros estimados. Al final de la práctica aparece el guión
completo con el código que evita trabajar con los menús en modo
gráfico (que es el peor modo de trabajar con Gretl).


***** Objetivo
1. Reproducir el primer ejemplo de regresión visto en clase.

2. Mostrar datos.
3. Generar gráficos.
4. Guardar un modelo para poder consultarlo más tarde.
5. Recuperar valores ajustados, errores estimados, etc.

***** Carga de datos
*/~Archivo --> Abrir datos --> Archivo de muestra~/* y en la pestaña
*/~Ramanathan~/* seleccione =data3-1=.

#+latex: {\vspace{0pt} \footnotesize \color{gray!70!black}
/o bien teclee en linea de comandos/:
#+NAME: Lectura del fichero de datos
#+begin_src hansl 
open data3-1
#+end_src
#+latex: }

** Actividad 1 - mostrar datos
***** Visualice los datos de precios y tamaños de las casas
- En la ventana principal de [[https://gretl.sourceforge.net/es.html][Gretl]], marque con el ratón ambas
  variables: =price=, =sqrt=.
- ``Pinche'' sobre ellas con el botón derecho del ratón.
- Seleccione */~mostrar valores~/* del menú desplegable que se ha
  abierto al pinchar.
  
  #+latex: {\vspace{1pt} \footnotesize \color{gray!70!black}
  /o bien teclee en linea de comandos/:
    #+NAME: Mostramos los valores de los datos en columna
    #+begin_src hansl 
    print -o price sqft
    #+end_src
  #+latex: }

#+latex: \vspace{-3pt}   
  
***** Ayuda
Para consultar la documentación sobre cualquier comando, puede emplear
el menú desplegable */~Ayuda~/* que aparece arriba, a la derecha de la
ventana principal de [[https://gretl.sourceforge.net/es.html][Gretl]].
  + */~Ayuda -> Guía de Instrucciones~/* y ``pinche'' sobre */~print~/*

#+latex: {\vspace{0pt} \footnotesize \color{gray!70!black}
/o bien teclee en linea de comandos/: =help print=
#+latex: }
    
** Actividad 2 - diagrama de dispersión
***** Scatter plot
- Marque =price= y =sqrt= (pulsando ~ctrl~ y pinchando con el botón
  derecho del ratón sobre ellas). Elija */~Gráfico de dos variables
  XY~/*
- Seleccione =sqft= como variable del eje X

  #+latex: {\vspace{1pt} \footnotesize \color{gray!70!black}
  /o bien teclee en linea de comandos/: =gnuplot price sqft=
  #+latex: }

***** Guardar gráfico como /icono/ para editarlo más tarde
- ``Pinche'' con el botón derecho sobre la ventana del gráfico.
- Seleccione */~Guardar a sesión como icono~/*

  #+latex: {\vspace{1pt} \footnotesize \color{gray!70!black} \color{gray!70!black}
  /o bien teclee en linea de comandos/:
    #+NAME: Guardamos scatterplot como icono
    #+begin_src hansl 
    RectaDeRegresion <- gnuplot price sqft
    #+end_src
    (=RectaDeRegresion= /es el nombre con el que se guardará el icono/)
  #+latex: }

En la zona inferior izquierda de la ventana principal puede ver una
serie de iconos. Uno de ellos es la */~vista de iconos de sesión~/*.

** Actividad 3 - Ajuste por MCO

***** Ajuste por MCO el modelo de regresión visto en clase
#+ATTR_BEAMER: :overlay <+->
- Estime el modelo mediante los menús desplegables: */~Modelo ->
  Mínimos Cuadrados Ordinarios~/*; indique a [[https://gretl.sourceforge.net/es.html][Gretl]] el regresando y los
  regresores y pulse */~Aceptar~/*.
  
  #+latex: {\vspace{1pt} \footnotesize \color{gray!70!black} \color{gray!70!black}
  /o bien teclee en linea de comandos/:
    #+begin_src hansl
    ols price 0 sqft
    #+end_src
    (/el cero/ =0= /indica el término constante/: =const=)
  #+latex: }
  
- ``Pinche'' */~Archivo~/* en la ventana del modelo estimado y
  seleccione */~guardar como un icono y cerrar~/*

  #+latex: {\vspace{1pt} \footnotesize \color{gray!70!black} \color{gray!70!black}
  /o bien teclee en linea de comandos/:
    #+NAME: Ajuste MCO que se guarda como icono
    #+begin_src hansl 
    Regresion  <- ols price 0 sqft
    #+end_src
  #+latex: }
    
- Recupere el modelo ``pinchando'' sobre su icono

  #+latex: {\vspace{1pt} \footnotesize \color{gray!70!black} \color{gray!70!black}
  /o teclee en linea de comandos el nombre que ha dado al icono
    seguido de/ =.show=, /es decir/:
    #+NAME: Mostramos la ventana del ajuste MCO
    #+begin_src hansl 
    Regresion.show
    #+end_src
  #+latex: }
  
** Actividad 4 - Recuperar los valores ajustados
***** Recuperemos los valores ajustados 
    :PROPERTIES:
    :BEAMER_ENV: block
    :BEAMER_ACT: <+->
    :END:
    
- Desde la ventana del modelo ajustado (recupérese con su icono),
  ``pinche'' en */~guardar -> valores estimados~/*. Elija como nombre
  =phat= (puede añadir una descripción de la variable). Pulse en
  */~Aceptar~/*
- Repita para guardar los =residuos= con el nombre =ehat=
  
  #+latex: {\vspace{1pt} \footnotesize \color{gray!70!black}
  /o bien teclee en linea de comandos/:
    #+NAME: Guardamos las series de valores ajustados y de errores
    #+begin_src hansl 
    series phat =  $yhat
    series ehat =  $uhat
    #+end_src
  #+latex: }
    
***** Mostremos las variables =price=, =sqft=, =phat= y =ehat=
    :PROPERTIES:
    :BEAMER_ENV: block
    :BEAMER_ACT: <2>
    :END:
#+ATTR_BEAMER: :overlay <+->
- Marque las 4 variables (~ctrl~ y ``pinchar'' con el botón derecho) y elija
  */~mostrar valores~/*
  
  #+latex: {\vspace{1pt} \footnotesize \color{gray!70!black}
  /o bien teclee en linea de comandos/: 
    #+begin_src hansl 
    print -o price sqft phat ehat
    #+end_src
    #+latex: }

** Actividad 5 - Otras formas de recuperar el ajuste
#+ATTR_BEAMER: :overlay <+>
- =phat2=: restar a los precios los errores
  
  Desde la ventana del modelo: */~Guardar -> Definir una nueva
  variable~/* y teclee:
  =phat2 = price - ehat=
  
  #+latex: {\vspace{1pt} \footnotesize \color{gray!70!black} \color{gray!70!black}
  /o bien teclee en linea de comandos/:
    #+NAME: Otras formas de calcular phat
    #+begin_src hansl 
    series phat2 = price - ehat
    #+end_src
  #+latex: }
    
- =phat2=: Cálculo /``chapucero''/: 52.351 + 0.139 /sqft/

  */~Guardar -> Definir una nueva variable~/* y teclee:
  #+latex: {\vspace{1pt} \footnotesize \color{gray!70!black} \color{gray!70!black}
    #+NAME: Otra forma chapucera de calcular phat
    #+begin_src hansl 
    series phat3 = 52.351 + 0.139*sqft
    #+end_src
  #+latex: }
  
- =phat2=: Cálculo correcto: \Estmc{\beta_1} + \Estmc{\beta_2} /sqft/

  */~Guardar -> Definir una nueva variable~/* y teclee:
  #+latex: {\vspace{1pt} \footnotesize \color{gray!70!black} \color{gray!70!black}
    #+NAME: Forma correcta de calcular phat
    #+begin_src hansl 
    series phat4 = $coeff[1] + $coeff[2]*sqft
    #+end_src
  #+latex: }
  o bien:
  #+latex: {\vspace{1pt} \footnotesize \color{gray!70!black} \color{gray!70!black}
    #+NAME: Otra forma correcta de calcular phat 
    #+begin_src hansl 
    series phat5 = $coeff(const) + $coeff(sqft)*sqft
    #+end_src
  #+latex: }

- Visualice los valores como ya hizo en la Actividad 1 de más arriba. ¿Hay diferencias?
  
  #+latex: {\vspace{1pt} \footnotesize \color{gray!70!black} \color{gray!70!black}
  /o bien teclee en linea de comandos/:
    #+NAME: Compare lo cálculos 
    #+begin_src hansl 
    print -o price phat phat2 phat3 phat4 
    #+end_src
  #+latex: }

#+latex: \vspace{10pt}
#+latex: \noindent
*Código completo de la práctica* ~EjPvivienda.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/EjPvivienda.inp}
#+LATEX: \clearpage

** COMMENT Resultado en Gretl

#+begin_src bash :results file :file EjPviviendaOUTPUT.txt :output-dir ~/gretl/resultados 
  gretlcli -b pub/EjPvivienda.inp 
#+end_src

#+RESULTS:
[[file:~/gretl/resultados/EjPviviendaOUTPUT.txt]]



#+LATEX: \clearpage


* Plano de regresión
   :PROPERTIES:
   :header-args: :tangle ./pub/scripts/PlanoRegresion.inp
   :END:

| Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/PlanoRegresion.inp][PlanoRegresion.inp]] |


- Carga de datos. Abra los menús desplegables: */~Archivo --> Abrir
  datos --> Archivo de muestra~/* y en la pestaña */~POE 4th ed.~/*
  seleccione =andy=.

  #+latex: {\vspace{1pt} \footnotesize \color{gray!70!black}
  /o bien teclee en linea de comandos/:
  #+NAME: Lectura del fichero de datos
    #+begin_src hansl 
open andy.gdt
    #+end_src
  #+latex: }
  
- Ajuste por MCO las ventas a los precios y gastos en publicidad:
  */~Modelo -> Mínimos Cuadrados Ordinarios~/*; indique a [[https://gretl.sourceforge.net/es.html][Gretl]] el
  regresando y los regresores y pulse */~Aceptar~/*.
  
  #+latex: {\vspace{1pt} \footnotesize \color{gray!70!black} \color{gray!70!black}
  /o bien teclee en linea de comandos/:
    #+begin_src hansl
    ols sales 0 price advert
    #+end_src
    (/el cero/ =0= /indica el término constante/: =const=)
  #+latex: }
  
- ``Pinche'' */~Archivo~/* en la ventana del modelo estimado y
  seleccione */~guardar como un icono y cerrar~/*

  #+latex: {\vspace{1pt} \footnotesize \color{gray!70!black} \color{gray!70!black}
  /o bien teclee en linea de comandos/:
    #+NAME: Ajuste MCO que se guarda como icono
    #+begin_src hansl 
    Regresion  <- ols sales 0 price advert
    #+end_src
  #+latex: }

- Observe el /plano de regresión/: abra la ventana del modelo ajustado
  y pinche en */~Gráficos -> Gráfico de variable estimada y observada
  -> Contra price y advert~/*

  #+latex: {\vspace{1pt} \footnotesize \color{gray!70!black} \color{gray!70!black}
    #+begin_src hansl :exports none
    # solo es posible visualizar el plano de regresion con los menus desplegables
    #+end_src
    #+latex: }

#+latex: \vspace{10pt}
#+latex: \noindent
*Código completo de la práctica* ~PlanoRegresion.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/PlanoRegresion.inp}
#+LATEX: \clearpage


* Simulación del ejemplo del precio de las viviendas con tres regresores
   :PROPERTIES:
   :header-args: :tangle ./pub/scripts/SimuladorEjPvivienda.inp
   :END:

| Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/SimuladorEjPvivienda.inp][SimuladorEjPvivienda.inp]] |
   
En este ejercicio con [[https://gretl.sourceforge.net/es.html][Gretl]] generaremos unos datos simulados para realizar regresiones MCO.

1) Simulamos series de datos de 500 observaciones
  
   + */~Archivo -> Nuevo conjunto de datos~/*, e indicamos el número
     de observaciones: 1500. Marcamos /de sección cruzada/ y
     continuamos adelante. Dejamos sin marcar ~empezar a introducir
     los valores de los datos~ y pulsamos ~Aceptar~.

   + o bien:
     #+begin_src hansl 
   nulldata 1500
     #+end_src

2) Generamos tres variables: =S= con distribución uniforme (35, 120);
   =D= con distribución Chi cuadrado con 5 grados de libertad que
   vamos a multiplicar por 3 y =U= con distribución Normal de media 0
   y desviación típica 40

   + */~Añadir -> Variable aleatoria~/* y se elige para cada
     variable el tipo de distribución, los valores de los parámetros y
     el nombre de la variable

   + o bien
     #+begin_src hansl 
   series S = randgen(U, 35, 120)
   series D = randgen(X, 5) * 3
   series U = randgen(N, 0, 40)
     #+end_src

3) Simulamos los precios según el modelo $\Vect{p} = 300\Vect{1} +
   5\Vect{s} - 2\Vect{d} + \Vect{u}$

   + */~Añadir -> Definir nueva variable~/* y tecleamos: ~P = 300 + 5*S - 2*D + U~

   + O bien 
     #+begin_src hansl
       series P = 300 + 5*S - 2*D + U
     #+end_src

4) Observe los estadísticos de las variables de modelo. En particular,
   ¿son ortogonales =S= y =D= respecto al regresor constante \Vect{1}?

   + */~Ver -> Estadísticos principales~/* con el ratón marcamos =D=,
     =S= y =P=.

   + O bien 
     #+begin_src hansl
       summary P S D
     #+end_src

5) El valor absoluto de la correlación entre =D= y =S= ¿es grande o
   pequeño?

   + */~Ver -> Matriz de correlación~/* y selecciones =D= y =S=.

   + O bien 
     #+begin_src hansl
       corr S D
     #+end_src

6) Observe los diagramas de dispersión de =P= con =S=, el de =P= con
   =D=, y el de los regresores =S= y =D=:

   + */~Ver -> Gráficos -> Gráfico X-Y (Scatter)~/*. Indicamos =S= como ~variable del eje x~. Indicamos =P= como ~variable del eje y~.

   + */~Ver -> Gráficos -> Gráfico X-Y (Scatter)~/*. Indicamos =D= como ~variable del eje x~. Indicamos =P= como ~variable del eje y~.

   + */~Ver -> Gráficos -> Gráfico X-Y (Scatter)~/*. Indicamos =S= como ~variable del eje x~. Indicamos =D= como ~variable del eje y~.

   + O bien 
     #+begin_src hansl
       scaterPS <- gnuplot P S
       scaterPD <- gnuplot P D
       scaterDS <- gnuplot D S
     #+end_src

     Nótese como dichos diagramas reflejan las correlaciones entre las distintas variables del modelo.

7) Ajuste por MCO =P= empleando =S= y =D=:

   + pinche en */~Modelo -> Mínimos Cuadrados Ordinarios~/* y selecciones =D= y =S=.

     - Elija =P= como regresando o "variable dependiente" (marque la opción ~Selección por defecto~).

     - Elija =S= y =D= como regresores o "Variables independientes". Pinche en ~Aceptar~.

     - En la ventana del modelo pinche en */~Archivo -> Guardar como icono y cerrar~/*.

     - Con el botón derecho del ratón, pinche sobre el icono del
       modelo estimado y seleccione ~Añadir a la tabla de modelos~.

   + O bien 
     #+begin_src hansl
       ModeloCompleto <- ols P 0 S D
       modeltab add
     #+end_src

   Observe que el ajuste recupera aproximadamente los valores de los
   parámetros del modelo simulado.

   Observe el /plano de regresión/: abra la ventana del modelo
   ajustado y pinche en */~Gráficos -> Gráfico de variable estimada y
   observada -> Contra S y D~/*

   
  
  - *Tarea adicional* Observe que el papel del parámetro $\beta_1$
    que acompaña al término constante es equilibrar los valores
    medios a ambos lados de la ecuación; es decir, asegurar que
    \[\media{\Vect{p}}=\Estmc{\beta_1}+\Estmc{\beta_2}\media{\Vect{s}}+\Estmc{\beta_3}\media{\Vect{d}}\]
    Verifique que efectivamente
    \[\Estmc{\beta_1}=\media{\Vect{p}}-\Estmc{\beta_2}\media{\Vect{s}}-\Estmc{\beta_3}\media{\Vect{d}}\]

    + Hágalo empleando una calculadora o indique el cálculo en el guión de Gretl con
      #+begin_src hansl	 
	## TAREA ADICIONAL ####
        scalar AjusteMediasC = mean(P) - $coeff(S)*mean(S) - $coeff(D)*mean(D)
        scalar beta1HatC     = $coeff(const)
	######################	 
      #+end_src

      /Otra manera de aludir a los betas estimados es generar una
      matriz columna con los betas: ~beta = $coeff~, de manera que
      ~beta[1,1]~, ~beta[2,1]~ y ~beta[3,1]~ son $\Estmc{\beta_1}$,
      $\Estmc{\beta_2}$ y $\Estmc{\beta_3}$ respectivamente./

** Omisión de regresores       
1) Si se omite el regresor =D= del ajuste ¿qué esperaría que ocurra
   con el parámetro asociado a la cte?

  + pinche en */~Modelo -> Mínimos Cuadrados Ordinarios~/*

    - En la lista de variables dependientes, pinche sobre =D= y pulse la flecha roja para eliminar dicha variable del
      modelo. Pinche en ~Aceptar~.

    - la ventana del modelo pinche en */~Archivo -> Guardar como icono y cerrar~/*.

    - añada este modelo a la ~Tabla de modelos~.

  + O bien 
    #+begin_src hansl
      ModeloSinD <- ols P 0 S
      modeltab add
    #+end_src

  ¿Confirman los resultados lo esperado respecto a los parámetros estimados?

  - *Tarea adicional* Recuerde que el papel del parámetro $\beta_1$
    que acompaña al término constante es equilibrar los valores
    medios a ambos lados de la ecuación; en este caso,
    \[\media{\Vect{p}}=\Estmc{\beta_1}+\Estmc{\beta_2}\media{\Vect{s}}\]
    Verifique que efectivamente
    \[\Estmc{\beta_1}=\media{\Vect{p}}-\Estmc{\beta_2}\media{\Vect{s}}\]

    + Hágalo empleando una calculadora o indique el cálculo en el guión de Gretl con
      #+begin_src hansl	 
        ## TAREA ADICIONAL ####
        scalar AjusteMediasNoD = mean(P) - $coeff(S)*mean(S)
        scalar beta1HatNoD = $coeff(const)
        ######################	 
      #+end_src
       
- Repita el experimento, pero esta vez incluyendo =D= y excluyendo =S=

  + pinche en */~Modelo -> Mínimos Cuadrados Ordinarios~/*

    - Elimine de la lista de regresores la variable =S=, e incluya =D= como regresor. Pinche en ~Aceptar~.

    - la ventana del modelo pinche en */~Archivo -> Guardar como icono y cerrar~/*.

    - añada este modelo a la ~Tabla de modelos~.

  + O bien 
    #+begin_src hansl
      ModeloSinS <- ols P 0 D
      modeltab add
    #+end_src
    donde ~modeltab show~ muestra la tabla de modelos ajustados.

  ¿Confirman los resultados lo esperado respecto a los parámetros estimados?

  + *Tarea adicional* Aquí $\beta_1$ asegura que
    \[\media{\Vect{p}}=\Estmc{\beta_1}+\Estmc{\beta_2}\media{\Vect{d}}\]
    Verifique que efectivamente
    \[\Estmc{\beta_1}=\media{\Vect{p}}-\Estmc{\beta_2}\media{\Vect{d}}\]

    + Hágalo empleando una calculadora o indique el cálculo en el guión de Gretl con
      #+begin_src hansl	 
	## TAREA ADICIONAL ####
        scalar AjusteMediasNoS = mean(P) - $coeff(D)*mean(D)
        scalar beta1HatNoD = $coeff(const)
	######################	 
      #+end_src

** Proyección omitiendo las constantes       
      
- ¿Y si calculamos la proyección ortogonal de los precios sobre =S=
  y =D= omitiendo la constante? ¿Qué espera que ocurra con los valores medios de =P=
  y del ajuste? Verifique su respuesta con el ordenador.

  + pinche en */~Modelo -> Mínimos Cuadrados Ordinarios~/*

    + Elija =S= y =D= como regresores, pero elimine la constante de la
      lista (/¡algo que jamás debe hacer en sus
      estimaciones!/). Pinche en ~Aceptar~.

    + la ventana del modelo pinche en */~Archivo -> Guardar como icono y cerrar~/*.

    + añada este modelo a la ~Tabla de modelos~.

  + O bien 
    #+begin_src hansl
      ModeloSin1 <- ols P S D
      modeltab add
    #+end_src

  ¿Confirman los resultados lo esperado respecto a los parámetros estimados?

  - *Tarea adicional* Aquí no hay un término constante, así que
    \[\media{\Vect{p}} \ne \Estmc{\beta_1}\media{\Vect{s}} + \Estmc{\beta_2}\media{\Vect{d}}\]
    El equilibro se da añadiendo la media de los errores (que por no
    existir término constante es distinta de cero).  Verifique que
    efectivamente
    \[\media{\Vect{p}} = \Estmc{\beta_1}\media{\Vect{s}} + \Estmc{\beta_2}\media{\Vect{d}} + \media{\res}\]

    + Hágalo empleando una calculadora o indique el cálculo en el guión de Gretl con
      #+begin_src hansl	 
       ## TAREA ADICIONAL ####
       scalar MediaLadoIzdo = mean(P)
       scalar MediaLadoDcho = $coeff(S)*mean(S) + $coeff(D)*mean(D) + mean($uhat)
       ######################	 
      #+end_src
      donde ~$uhat~ son los residuos de la  última regresión realizada.
 
    Este ajuste sin constante, *y que por tanto no debemos llamar
    /regresión MCO/*, no logra equiparar correctamente los valores
    medios de ambos lados de la ecuación. Los únicos elementos
    disponibles para intentar dicho ajuste han sido los vectores de
    datos =S= y =D=, que tienen medias distintas de cero. Pero
    simultáneamente dichos vectores son necesarios para lograr el
    ajuste de las pendientes. Por ello los resultados al omitir la
    constante pueden ser desastrosos.
 
    # Es más, puesto que con cualquiera de los dos regresores es
    # posible de ajustar las medias (si se juega adecuadamente con los
    # betas), esta doble posibilidad se traduce en una mayor
    # incertidumbre en los valores estimados (¿qué variable es más
    # importante para ajustar la media?).

    # Observe en la tabla de modelos cómo han aumentado notablemente
    # las desviaciones típicas de los valores estimados en el modelo
    # sin término constante. Sin embargo, si se fija en los
    # coeficientes de determinación de dicha tabla de modelos, parece
    # que se ha logrado un mejor ajuste. El motivo es que, aunque
    # Gretl indique que calcula el coeficiente de determinación, no es
    # cierto. El programa Gretl realiza un cálculo alternativo cuando
    # el modelo carece de término constante.

    # Calcule los verdaderos coeficientes de determinación y
    # determinación ajustado. Hágalo tecleando las siguientes
    # instrucciones en la consola de Gretl
    # #+begin_src hansl	 
    # 	R2Sin1         = 1 - $ess/(($T-1) * var(P))
    #   R2AjustadoSin1 = 1 - ($T-1)/($T-2)*(1 - R2Sin1)
    # #+end_src

** ``Ortogonalizando'' los regresores no constantes respecto de las constantes
    
1) ¿Hay alguna forma de “ortogonalizar” =S= y =D= respecto de la
   constante?... ¡Si!, basta restar las medias (generar nuevos
   regresores en desviaciones respecto a su media):
   
  + */~Añadir -> Definir nueva variable~/* y escribimos ~series S0 =
    S - mean(S)~
  + */~Añadir -> Definir nueva variable~/* y escribimos ~series D0 =
    D - mean(D)~
  + O bien 
    #+begin_src hansl
      series S0 = S - mean(S)
      series D0 = D - mean(D)
    #+end_src

- Verifique que la media de =S0= y =D0= es cero. Ajuste por MCO los siguientes modelos:
  \[P = \beta_1 + \beta_2 S0 + \beta_3 D0\]
  y
  \[P = \beta_2 S0 + \beta_3 D0\]
  
  Compare los resultados entre ambos y con el modelo completo original.

  #+begin_src hansl
    ModeloCompEnDesviaciones <- ols P 0 S0 D0
    modeltab add
    ModeloEnDesviaciones <- ols P S0 D0
    modeltab add
    modeltab show
  #+end_src

  + Compare la estimación de $\beta_1$ del =ModeloCompEnDesviaciones=
    con la media de =P=.

  + ¿Se le ocurre alguna explicación para este resultado?

  + Observe en la tabla de modelos las similitudes del primer modelo
    en desviaciones con las obtenidas con el modelo completo
    original... ¡Todo es idéntico salvo la estimación de $\beta_1$!

  + Observe que aunque las pendientes estimadas toman los mismos
    valores en ambos modelos en desviaciones, la incertidumbre
    asociada en el caso del modelo en desviaciones sin contante es
    mucho mayor

#+latex: \vspace{10pt}
#+latex: \noindent
*Código completo de la práctica* ~SimuladorEjPvivienda.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/SimuladorEjPvivienda.inp}
#+LATEX: \clearpage


* Repetición del ejemplo pero introduciendo correlación entre regresores
   :PROPERTIES:
   :header-args: :tangle ./pub/scripts/SimuladorEjPvivienda2.inp
   :END:

   | Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/SimuladorEjPvivienda2.inp][SimuladorEjPvivienda2.inp]] |

En la simulación de la práctica anterior no había una correlación muy
fuerte entre =S= y =D=. En ejemplos reales podemos encontrar una mayor
riqueza de interrelaciones entre regresores.  Para experimentar las
consecuencias, vamos a repetir todo el ejercicio pero introduciendo un
factor común entre =S= y =D= que genere correlación entre ambos
regresores.

- Los datos :: Vamos a variar el modo de generar los datos respecto a la práctica anterior.

  - Genere un factor común =C= con distribución normal de esperanza 40
    y desviación típica 20: */~Añadir -> Definir nueva variable~/* y
    escribimos ~series C = randgen(N, 40, 20)~

  - Genere un vector de datos de superficies con distribución uniforme
    entre 20 y 70 y súmele =C=: */~Añadir
    -> Definir nueva variable~/* y escribimos ~series S = randgen(U, 20, 70) + C~

  - Genere un vector de tiempos de viaje con distribución Chi cuadrado
    con 8 grados de libertad, y súmele 100 y réstele C: */~Añadir ->
    Definir nueva variable~/* y escribimos ~series D = randgen(X, 8) +
    100 - C~

  - Genere un vector de perturbaciones con distribución Normal de
    media 0 y desviación típica 40. */~Añadir -> Definir nueva
    variable~/* y escribimos ~series U = randgen(N, 0, 40)~

  - O bien
    #+NAME: Simulación de regresores S y D con correlación
    #+begin_src hansl
      nulldata 1500
      series C = randgen(N, 40, 20)
      series S = randgen(U, 20, 70) + C
      series D = randgen(X, 8) + 100 - C
      series U = randgen(N, 0, 40)
    #+end_src


-  El modelo :: que de nuevo simulamos es: $\Vect{p} = 300\Vect{1} +
  5\Vect{s} - 2\Vect{d} + \Vect{u}$

  + */~Añadir -> Definir nueva variable~/* y tecleamos: ~P = 300 + 5*S - 2*D + U~

  + O bien 
    #+NAME: Simulación del regresando P
    #+begin_src hansl
      series P = 300 + 5*S - 2*D + U
    #+end_src


- Actividades :: 
  Repita todas las actividades de la práctica anterior pero con estos
  nuevos datos simulados.  Preste especial atención a cuáles son las
  diferencias entre esta simulación y la anterior sin correlación
  entre =S= y =D=.

  Como ya están descritas en la práctica anterior, a continuación tan solo mostrare el guión modificado.
  #+begin_src hansl :exports none
    summary P S D
    
    corr S D
    
    scaterPS <- gnuplot P S
    scaterPD <- gnuplot P D
    scaterDS <- gnuplot D S
    
    ModeloCompleto <- ols P 0 S D
    modeltab add
    
    ## TAREA ADICIONAL ####
    scalar AjusteMediasC = mean(P) - $coeff(S)*mean(S) - $coeff(D)*mean(D)
    scalar beta1HatC     = $coeff(const)
    ######################
    
    ModeloSinD <- ols P 0 S
    modeltab add
    
    ## TAREA ADICIONAL ####
    scalar AjusteMediasNoD = mean(P) - $coeff(S)*mean(S)
    scalar beta1HatNoD = $coeff(const)
    ######################
    
    ModeloSinS <- ols P 0 D
    modeltab add
    
    ## TAREA ADICIONAL ####
    scalar AjusteMediasNoS = mean(P) - $coeff(D)*mean(D)
    scalar beta1HatNoD = $coeff(const)
    ######################
    
    ModeloSin1 <- ols P S D
    modeltab add
    
    ## TAREA ADICIONAL ####
    scalar MediaLadoIzdo = mean(P)
    scalar MediaLadoDcho = $coeff(S)*mean(S) + $coeff(D)*mean(D) + mean($uhat)
    ######################
    
    series S0 = S - mean(S)
    series D0 = D - mean(D)
    
    ModeloCompEnDesviaciones <- ols P 0 S0 D0
    modeltab add
    ModeloEnDesviaciones <- ols P S0 D0
    modeltab add
    modeltab show
  #+end_src

#+LATEX: \clearpage
#+latex: \noindent
*Código completo de la práctica* ~SimuladorEjPvivienda2.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/SimuladorEjPvivienda2.inp}
#+LATEX: \clearpage


* Más sobre la ortogonalización de regresores 
   :PROPERTIES:
   :header-args: :tangle ./pub/scripts/SimuladorEjPvivienda3.inp
   :END:

   | Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/SimuladorEjPvivienda3.inp][SimuladorEjPvivienda3.inp]] |
   
En el ejemplo anterior hemos visto que al generar nuevos regresores
=S0= y =P0= que son las componentes de =S= y =P= perpendiculares a las
constantes, y usarlos en sustitución de los regresores originales,
hemos logrado nuevos ajustes en los que incluir u omitir el regresor
constante no cambia el valor de las pendientes estimadas.

** Empleando regresores no constantes que son perpendiculares entre si

Veamos si es posible generalizar este resultado, es decir, si al
emplear como regresor la componente de =S= perpendicular a =P= y la
constante, podemos ajustar =P= con tres regresores perpendiculares
entre sí, de tal manera que omitir cualesquiera de los regresores no
afecta a los parámetros estimados correspondientes a los regresores
que sí se mantienen en el ajuste.

+ Simulamos el modelo de la práctica anterior
#+begin_src hansl :noweb yes
  <<Simulación de regresores S y D con correlación>>
  <<Simulación del regresando P>>
#+end_src

+ Ajustamos los primeros tres modelos de la práctica anterior y los
  guardamos como iconos.
  
#+begin_src hansl :noweb yes
  ModeloCompleto <- ols P 0 S D
  modeltab add    
  ModeloSinD <- ols P 0 S
  modeltab add
  ModeloSinS <- ols P 0 D
  modeltab add
  ModeloSin1 <- ols P S D
  modeltab add
#+end_src

+ El último ajuste es una proyección ortogonal sin término constante
  (no una regresión). Calculemos el coeficiente de determinacion y el
  coeficiente de determinacion ajustado calculando explícitamente su
  fórmula.
  
#+begin_src hansl :noweb yes
  # calculo del coeficiente de determinacion
  scalar R2Sin1 = 1 - $ess/(($T-1) * var(P))
  scalar R2AjustadoSin1 = 1 - ($T-1)/($T-2)*(1 - R2Sin1)
#+end_src

*** Regresiones auxiliares

+ Calculamos la componente de =D= que es ortogonal a los vectores
  constantes y la denominamos =D0=

#+begin_src hansl :noweb yes
  # ortogonalizamos D respecto de las constantes
  series D0 = D - mean(D)
  # o de manera equivalente
  ols D 0 
  series D0 = $uhat

#+end_src

+ Calculamos la componente de =S= que es ortogonal a los vectores
  constantes y a =D= y la denominamos =SpD=

#+begin_src hansl :noweb yes
  # ortogonalizamos S respecto de las constantes y D
  ols S 0 D
  series SpD = $uhat
#+end_src

*** Ajuste de =P= con los nuevos regresores

+ Mediante una regresión ajustamos por MCO =P= a los nuevos regresores

#+begin_src hansl :noweb yes
  ModeloCompleto2   <- ols P 0 SpD D0
  modeltab add
#+end_src

+ Mediante una regresión ajustamos por MCO =P= únicamente al regresor constante

#+begin_src hansl :noweb yes
  ModeloSolo1       <- ols P 0
  modeltab add
#+end_src

+ Mediante una proyección ajustamos =P= a =SpD=

#+begin_src hansl :noweb yes
  ModeloSoloS       <- ols P SpD
  modeltab add
#+end_src

+ Mediante una proyección ajustamos =P= a =D0=

#+begin_src hansl :noweb yes
  ModeloSoloD       <- ols P D0
  modeltab add
#+end_src

+ Compare los resultados de los distintos ajustes: los valores de los
  parámetros y el ajuste medido con el $R^2$ corregido

#+begin_src hansl :noweb yes
  modeltab show
#+end_src

** Ajustes aún más curiosos 
#+begin_src hansl
  ## Dos ajustes curiosos 
#+end_src
En los siguientes ajustes lo que se mantiene es el valor del parámetro
correspondiente la constante del modelo original (aunque no aparezca
explícitamente ningún regresor constante en el ajuste... ahí radica la
curiosidad).

*** Una primera proyección auxiliar
Lo primero es obtener la componente del vector \Vect{1} que es
perpendicular a =S= y a =D= mediante una primera proyección auxiliar
(no la llamaré regresión, pues el espacio sobre el que proyectamos no
contiene los vectores constantes). Llamaré =cte= a dicha componente
(pero obviamente no es un vector constante):
#+begin_src hansl
  ols 0 S D                # proyeccion del vector 1 sobre S y D
  series cte = $uhat       # componente del vector 1 que es perpendicular a S y a D
#+end_src


*** Primer ajuste curioso
En una nueva /proyección/ auxiliar obtenemos la componente de =S= que
es perpendicular a =cte= y a =D=, que llamaré =SpD= (componente de =S=
perpendicular a =D= y a =cte=).
#+begin_src hansl
  ##################### Primer ajuste curioso ##################
  ols S cte D
  series SpD = $uhat       # componente de S que es perpendicular a "cte" y a D
#+end_src
Y ahora realizamos la /regresión/ de =P= sobre el mismo subespacio que
en modelo original, pero empleando tres regresores que son ortogonales
entre si, y tales que el parámetro de =cte= es igual al
correspondiente a la constante del modelo original y el de =SpD= al
del parámetro de =S= en la /proyección/ de =P= sobre =S= y =D=
(omitiendo la constante).
#+begin_src hansl
  # regresion MCO que mantiene la pendiente de S del ajuste sin cte
  ModeloCompletoAlternativo1 <- ols P cte SpD D 
  modeltab add 
#+end_src

*** Segundo ajuste curioso
Alternativamente podemos dar los pasos análogos, pero usando la
/proyección/ auxiliar de =D= sobre =cte= y =S=.
#+begin_src hansl
  ##################### Segundo ajuste curioso ##################
  ols D cte S
  series DpS = $uhat       # componente de D que es perpendicular a cte y a S
  ## regresion MCO que mantiene la pendiente de D del ajuste sin cte
  ModeloCompletoAlternativo2 <- ols P cte DpS S 
  modeltab add  
  modeltab show
#+end_src

Compare los resultados en la tabla de modelos.

#+LATEX: \clearpage
#+latex: \noindent
*Código completo de la práctica* ~SimuladorEjPvivienda3.inp~
# +latex: \vspace{10pt}
\lstinputlisting{scripts/SimuladorEjPvivienda3.inp}
#+LATEX: \clearpage
