#+title:  Lección 6
#+author: Marcos Bujosa
#+STARTUP: show4levels
#+LANGUAGE: es-es

#+EXPORT_FILE_NAME: pub/Lecc06

# +OPTIONS: toc:nil
#+OPTIONS: tags:nil

#+LATEX_CLASS: article

#+LATEX_HEADER: \usepackage[spanish]{babel}
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+LaTeX_HEADER: \usepackage[svgnames,x11names]{xcolor}
#+LaTeX_HEADER: \hypersetup{linktoc = all, colorlinks = true, urlcolor = DodgerBlue4, citecolor = PaleGreen1, linkcolor = SpringGreen4}
#+LaTeX_HEADER: \PassOptionsToPackage{hyphens}{url}
#+LaTeX_HEADER: \usepackage{nacal}

#+LaTeX_HEADER: \usepackage{framed}

#+LaTeX_HEADER: \usepackage{listings}
#+LaTeX_HEADER: \input{hansl.tex}
#+LaTeX_HEADER: \lstnewenvironment{hansl-gretl}
#+LaTeX_HEADER: {\lstset{language={hansl},basicstyle={\ttfamily\footnotesize},numbers,rame=single,breaklines=true}}
#+LaTeX_HEADER: {}
#+LaTeX_HEADER: \newcommand{\hansl}[1]{\lstset{language={hansl},basicstyle={\ttfamily\small}}\lstinline{#1}}
# +LaTeX_HEADER: \lstset{backgroundcolor=\color{white},basicstyle=\ttfamily\footnotesize,breaklines=true, captionpos=b,commentstyle=\color{mygreen},escapeinside={\%*}{*)}, keywordstyle=\color{blue},stringstyle=\color{mymauve}, }
# +LaTeX_HEADER: \lstset{backgroundcolor=\color{lightgray!20},basicstyle=\ttfamily\footnotesize,breaklines=true, }
#+LaTeX_HEADER: \lstset{backgroundcolor=\color{lightgray!20}, }

#+name: setup-listings
#+begin_src emacs-lisp :exports none :results silent
  (setq org-latex-listings 'listings)
  (setq org-latex-custom-lang-environments
  	;'((emacs-lisp "common-lispcode")))
  	'((emacs-lisp "hansl-gretl")))
  (setq org-latex-listings-options
	'(("frame" "lines")
	  ("basicstyle" "\\scriptsize")
	  ("basicstyle" "\\ttfamily")
	  ("numbers=none" "left")
	  ("backgroundcolor=\\color{lightgray!20}")
	  ("numberstyle" "\\tiny")))
  (setq org-latex-to-pdf-process
	'("pdflatex -interaction nonstopmode -output-directory %o %f"
	"pdflatex -interaction nonstopmode -output-directory %o %f"
	"pdflatex -interaction nonstopmode -output-directory %o %f"))
  (org-add-link-type
   "latex" nil
   (lambda (path desc format)
     (cond
      ((eq format 'html)
       (format "<span class=\"%s\">%s</span>" path desc))
      ((eq format 'latex)
       (format "\\%s{%s}" path desc)))))
#+end_src

# \lstnewenvironment{code}
#     {\lstset{language=haskell,
#     basicstyle=\small\ttfamily,
#     numbers=left,
#     numberstyle=\tiny\color{gray},
#     backgroundcolor=\color{lightgray},
#     firstnumber=auto
#     }}
#     {}

#+bibliography: ref.bib

# +latex: \clearpage

#+LATEX: \clearpage

* Varianza de los estimadores
   :PROPERTIES:
   :header-args: :tangle ./pub/scripts/EjPvivienda3.inp
   :END:

| Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/EjPvivienda3.inp][EjPvivienda3.inp]] |


Observe la matriz \InvXTX, del ejemplo del ``precio de las viviendas''.
\begin{displaymath}
   \InvXTX=
   \begin{bmatrix}
     9.1293e-01 & -4.4036e-04\\
     -4.4036e-04 & 2.3044e-07
   \end{bmatrix};
\end{displaymath}    
¿Qué estimación cree que es más fiable, la de la pendiente o la de la
constante?

+ Calcule dicha matriz $\InvXTX$ con Gretl.

#+begin_src hansl 
open data3-1
matrix X      = {const, sqft}
matrix invXTX = invpd(X'X)
print invXTX 
#+end_src

+ Realice la regresión de los precios sobre la superficie y añada el
  ajuste a la tabla de modelos (la opción ~--vcv~ muestra la matriz de
  varianzas y covarianzas de los estimadores ($\cvarM{}\InvXTX$) que
  Gretl estima con la muestra empleada en el ajuste ~ols~). Compruebe
  que si multiplica la matriz =invXTX= por la cuasivarianza de los
  errores obtiene el mismo resultado.
#+begin_src hansl 
ols price const sqft --vcv
modeltab add                              # incluimos el modelo a la tabla de modelos
matrix cv2invXTX = $ess/$df * invXTX 
print cv2invXTX
#+end_src

+ Repita el punto anterior pero con las siguientes modificaciones:
  
  1) con todos los datos excepto los de la última vivienda
     #+begin_src hansl 
smpl 1 13                                 # quitamos la primera observacion
ols price const sqft --vcv
modeltab add                              # incluimos el modelo a la tabla de modelos
smpl full                                 # recuperamos toda la muestra
     #+end_src
     
  2) con todos los datos excepto los de las últimas dos viviendas
     #+begin_src hansl 
smpl 2 14                                 # quitamos la ultima observacion
ols price const sqft --vcv
modeltab add                              # incluimos el modelo a la tabla d
smpl full                                 # recuperamos toda la muestra
     #+end_src

  3) con todos los datos excepto los de la primera y la última viviendas
     #+begin_src hansl 
smpl 2 13                                 # quitamos la primera y la ultima observaciones
ols price const sqft --vcv
modeltab add                              # incluimos el modelo a la tabla de modelos
modeltab show                             # MOSTRAMOS TODOS LOS MODELOS a la vez
     #+end_src


+ ¿Confirman los resultados de estas regresiones su respuesta a la
  primera pregunta?

#+LATEX: \clearpage
#+latex: \vspace{10pt}
#+latex: \noindent
** Código completo de la práctica ~EjPvivienda3.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/EjPvivienda3.inp}
#+LATEX: \clearpage



* Un experimento de Montecarlo
   :PROPERTIES:
   :header-args: :tangle ./pub/scripts/samplinghouses0.inp
   :END:

| Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/samplinghouses0.inp][samplinghouses0.inp]] |

Cargue los datos del ejemplo de los precios de casas unifamiliares
~data3-1.gdt~. Estime el modelo visto en clase. Guárdelo como
icono. También debe guardar como icono el diagrama de dispersión entre
=sqrt= y =price=.
#+begin_src hansl 
open data3-1
Modelo0  <- ols price 0 sqft
Scatter0 <- gnuplot price sqft --output=display
#+end_src

Vamos a simular este modelo generando nuevos datos por Montecarlo.
    
+ Genere una serie con la parte sistemática del modelo (empleando
  valores parecidos a los estimados):
  #+begin_src hansl 
series x  = sqft
series y1 = 52 + 0.14*x
  #+end_src

+ Genere una serie de perturbaciones con distribución normal, con
  esperanza nula y varianza $39$ un valor parecido al obtenido con los
  datos originales
  #+begin_src hansl 
series u1 = randgen(N, 0, 39)
  #+end_src

+ Genere una nueva serie de precios sumando a la parte
  sistemática las perturbaciones generadas en el paso anterior
  #+begin_src hansl 
# Datos de precios simulados
series y1 = ys + u1
  #+end_src
  
+ Con los nuevos datos de precios simulados ajuste el modelo de
  regresión de clase. ¿Se parecen los resultados?  Grafique la nube de
  puntos ~x,y~ ¿Observa diferencias respecto al diagrama de dispersión
  original?
  #+begin_src hansl 
Modelo1  <- ols y1 0 x
Scatter1 <- gnuplot y1 x --output=display
  #+end_src

+ Repita los pasos pasos anteriores con nuevas simulaciones y observe
  los cambios.
  #+begin_src hansl 
series u2 = randgen(N, 0, 39)
series y2 = ys + u2
Modelo2  <- ols y2 0 x
Scatter2 <- gnuplot y2 x --output=display
  #+end_src


#+LATEX: \clearpage
#+latex: \vspace{10pt}
#+latex: \noindent
** Código completo de la práctica ~samplinghouses0.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/samplinghouses0.inp}
#+LATEX: \clearpage



* Repitiendo el experimento de Montecarlo muchas veces

| Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/samplinghouses1.inp][samplinghouses1.inp]] |

Vamos a simular el modelo de la práctica anterior 10000 veces para ver
hasta qué punto estamos replicando los resultados originales.

Cargue los datos del ejemplo de los precios de casas unifamiliares
~data3-1.gdt~ y estime el modelo visto en clase. Guárdelo como icono
para poder consultar los resultados más tarde.

#+begin_src hansl :tangle ./pub/scripts/samplinghouses1.inp
open data3-1.gdt
Modelo <- ols price 0 sqft
#+end_src

+ Como antes, genere una nueva serie con la parte sistemática del
  modelo empleando valores de los parámetros parecidos a los
  estimados.
  #+begin_src hansl :tangle ./pub/scripts/samplinghouses1.inp
  series x  = sqft
  series ys = 52 + 0.14*x
  #+end_src
      
+ Defina un escalar =s= con el valor aproximado de la desviación
  típica de los residuos del modelo original.
  #+begin_src hansl :tangle ./pub/scripts/samplinghouses1.inp
  scalar s  = 39
  #+end_src
      
+ Especifique un bucle para realizar 10000 iteraciones y que almacene
  los coeficientes estimados (=--progressive=) pero sin mostrar los
  resultados (=--quiet=) de cada iteración. /Lea antes la
  documentación sobre/ ~loops~.

  Dentro del bucle indicaremos una serie de operaciones y órdenes que
  se describen más abajo
  #+begin_src hansl :noweb tangle :tangle ./pub/scripts/samplinghouses1.inp
  loop 10000 --progressive --quiet
     <<Simulamos el regresando y ajustamos por MCO>>
     <<Almacenamos los parámetros estimados>>
     <<Mostramos los resultados>>
     <<Guardamos los resultados en el disco>>
  endloop  
  #+end_src
      
      
    1) $\dots$ dentro del bucle introduzca las instrucciones para
       simular en cada iteración un nuevo vector de precios (sumando
       unas perturbaciones con media cero y desviación típica =s=. Y
       realice la correspondiente regresión.
       #+name: Simulamos el regresando y ajustamos por MCO
       #+begin_src hansl
	series y = ys + randgen(N, 0, s)
	ols y const x
       #+end_src

    2) Almacene los valores estimados de los betas correspondientes a
       la constante, la pendiente y la cuasivarianza varianza de los
       residuos
       #+name: Almacenamos los parámetros estimados
       #+begin_src hansl
	scalar b1   = $coeff(const)
	scalar b2   = $coeff(x)
	scalar cs2  = $ess/$df                      # cuasivarianza de los errores
       #+end_src

    3) Indique que Gretl muestre el resumen estadístico de los
       parámetros estimados en las 10000 iteraciones.
       #+name: Mostramos los resultados
       #+begin_src hansl
	print b1 b2 cs2
       #+end_src

    4) Guarde los parámetros estimados en el disco
       #+name: Guardamos los resultados en el disco
       #+begin_src hansl
	store "@workdir\coef.gdt" b1 b2 cs2
       #+end_src
            
  (/Puede almacenar dentro del bucle otros estadísticos (varianza
  estimada, coeficiente de determinación, etc.) para observar el
  comportamiento de los valores obtenidos en este experimento de
  Montecarlo/.)
      
+ Para analizar en detalle los valores obtenidos y almacenados en el
  fichero ~coef.gdt~, Gretl debe abrir y leer dicho fichero. Lo
  podemos indicar en este mismo guión, pero Gretl abrirá una nueva
  sesión y perderemos lo calculado con el bucle y que no haya sido
  guardado en el fichero (no quiere hacerlo así, entonces tendrá que
  abrir una segunda sesión de Gretl y cargar a ahí los datos del
  fichero ~coef.gdt~).
  #+begin_src hansl :tangle ./pub/scripts/samplinghouses1.inp
   open "@workdir\coef.gdt"
  #+end_src

+ Observe los valores máximos y mínimos estimados, y compárelos con
  los valores indicados en la simulación =b1=52=, =b2=0.14= y
  =s2=39^2=1521= (verá que en algunos casos lo estimado dista mucho
  del verdadero valor de los parámetros). Observe el histograma de los
  valores obtenidos para los parámetros
  #+begin_src hansl :tangle ./pub/scripts/samplinghouses1.inp
  summary   --simple
  freq b1   --normal --silent --plot="display"
  freq b2   --normal --silent --plot="display"
  freq cs2  --normal --silent --plot="display"
  #+end_src

+ Ejecute el guión y coteje los resultados de los estadísticos
  descriptivos de los betas estimados con los parámetros estimados en
  el modelo original (del de los datos originales visto en clase).
  
# +LATEX: \clearpage
#+latex: \vspace{10pt}
#+latex: \noindent
** Código completo de la práctica ~samplinghouses1.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/samplinghouses1.inp}
#+LATEX: \clearpage

* Repitiendo el experimento de Montecarlo muchas veces (Matriz de covarianzas)
   :PROPERTIES:
   :header-args: :tangle ./pub/scripts/samplinghouses2.inp
   :END:

Complete el experimento de Montecarlo de la Práctica [[Repitiendo el
experimento de Montecarlo muchas veces]] de más arriba con el
siguiente añadido:

+ Antes del bucle obtenga la matriz $\InvXTX$ y defina tres escalares
  =m11=, =m12= y =m22= correspondientes a los elementos (1,1), (1,2) y
  (2,2) de la matriz.
  #+begin_src hansl
  open data3-1.gdt
  series x  = sqft
  series ys = 52 + 0.14*x
  scalar s  = 39

  matrix X   = {const, sqft}
  matrix invXTX = invpd(X'X) # inversa de X'X
  scalar m11 = invXTX[1,1]
  scalar m21 = invXTX[2,1]
  scalar m22 = invXTX[2,2]
  #+end_src

+ Dentro del bucle incluya dichos escalares =m11=, =m12= y =m22= en la
  lista de parámetros a guardar

  #+begin_src hansl :noweb yes
  loop 10000 --progressive --quiet
     <<Simulamos el regresando y ajustamos por MCO>>
     <<Almacenamos los parámetros estimados>>
     <<Mostramos los resultados>>
     store "@workdir\coef.gdt" b1 b2 cs2 m11 m21 m22    
  endloop
  open "@workdir\coef.gdt"
  summary   --simple  b1 b2 cs2
  freq b1   --normal --silent --plot="display"
  freq b2   --normal --silent --plot="display"
  freq cs2  --normal --silent --plot="display"
  #+end_src

+ Finalmente, genere una matriz =S= de varianzas y covarianzas
  muestrales de las estimaciones de los betas obtenidos en las 10000
  iteraciones. Compárela con el promedio las matrices
  $\cvarM{}\InvXTX$ cuyos elementos (1,1), (1,2) y (2,2) son los
  escalares =m11=, =m12= y =m22= (que guardamos en el punto anterior)
  multiplicados por la media de las cuasivarianzas estimadas =cs2=.
  #+begin_src hansl 
  matrix s2invXTXhat = {var(b1), cov(b1,b2); cov(b2,b1), var(b2)}
  matrix s2invXTX    = mean(cs2)*{m11[1],m21[1];m21[1],m22[1]}
  print s2invXTX s2invXTXhat
  #+end_src

+ En promedio ¿es $\Estmd{\cvarM{}}\InvXTX$ un buen estimador de las
  varianzas y covarianzas de los parámetros beta estimados en la
  simulación?
  
#+LATEX: \clearpage
#+latex: \vspace{10pt}
#+latex: \noindent
** Código completo de la práctica ~samplinghouses2.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/samplinghouses2.inp}
#+LATEX: \clearpage


* Repitiendo el experimento de Montecarlo muchas veces (perturbaciones con distribuciones no Gaussianas)
   :PROPERTIES:
   :header-args: :tangle ./pub/scripts/samplinghouses3.inp
   :END:

Complete el experimento de Montecarlo de la práctica anterior pero
generando perturbaciones con distribución no normal (aunque con
esperanza nula). Para ello

+ Consulte la documentación sobre la función ~randgen~.
  
+ Repita los experimentos del ejercicio anterior pero generando
  perturbaciones con distribuciones distintas de la normal. Por
  ejemplo pruebe con

  - Distribución uniforme: ~series U = randgen(u, -5, 5)~

  - Distribución beta (centrada): ~series U = randgen(beta, 0.5, 0.5) - 0.5~

  - Distribución chi cuadrado (centrada): ~series U = randgen(X, 3) - 3~

+ Observe los histogramas y distribuciones de frecuencia así como los
  contrastes de normalidad. ¿Cambia mucho la distribución de los
  estimadores de los betas? ¿Y la del estimador de la varianza
  $\sigma^2$ de las perturbaciones?

+ En promedio ¿es $\Estmd{\cvarM{}}\InvXTX$ un buen estimador de las
  varianzas y covarianzas de los parámetros beta estimados en la
  simulación incluso cuando las preturbaciones tienen distribución muy
  distinta a la gausiana?

  #+begin_src hansl :noweb yes :exports none
  open data3-1.gdt
  series x  = sqft
  series ys = 52 + 0.14*x
  scalar s  = 39

  matrix X   = {const, sqft}
  matrix invXTX = invpd(X'X) # inversa de X'X
  scalar m11 = invXTX[1,1]
  scalar m21 = invXTX[2,1]
  scalar m22 = invXTX[2,2]

  loop 10000 --progressive --quiet
     series U = randgen(u, -5,  5)              # Descomente el que corresponda
     #series U = randgen(beta, 0.5, 0.5) - 0.5   # Descomente el que corresponda
     #series U = randgen(X, 3) - 3               # Descomente el que corresponda
     y = ys + U
     ols y const x
     <<Almacenamos los parámetros estimados>>
     <<Mostramos los resultados>>
     store "@workdir\coef.gdt" b1 b2 cs2 m11 m21 m22    
  endloop
  open "@workdir\coef.gdt"
  summary   --simple  b1 b2 cs2
  freq b1   --normal --silent --plot="display"
  freq b2   --normal --silent --plot="display"
  freq cs2  --normal --silent --plot="display"

  matrix s2invXTXhat = {var(b1), cov(b1,b2); cov(b2,b1), var(b2)}
  matrix s2invXTX    = mean(cs2)*{m11[1],m21[1];m21[1],m22[1]}
  print s2invXTX s2invXTXhat
  #+end_src

# +LATEX: \clearpage
#+latex: \vspace{10pt}
#+latex: \noindent
** Código completo de la práctica ~samplinghouses3.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/samplinghouses3.inp}
#+LATEX: \clearpage
