#+title:  Lección 5
#+author: Marcos Bujosa
#+STARTUP: show4levels
#+LANGUAGE: es-es

#+EXPORT_FILE_NAME: pub/Lecc05

# +OPTIONS: toc:nil
#+OPTIONS: tags:nil

#+LATEX_CLASS: article

#+LATEX_HEADER: \usepackage[spanish]{babel}
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+LaTeX_HEADER: \usepackage[svgnames,x11names]{xcolor}
#+LaTeX_HEADER: \hypersetup{linktoc = all, colorlinks = true, urlcolor = DodgerBlue4, citecolor = PaleGreen1, linkcolor = SpringGreen4}
#+LaTeX_HEADER: \PassOptionsToPackage{hyphens}{url}
#+LaTeX_HEADER: \usepackage{nacal}

#+LaTeX_HEADER: \usepackage{framed}

#+LaTeX_HEADER: \usepackage{listings}
#+LaTeX_HEADER: \input{hansl.tex}
#+LaTeX_HEADER: \lstnewenvironment{hansl-gretl}
#+LaTeX_HEADER: {\lstset{language={hansl},basicstyle={\ttfamily\footnotesize},numbers,rame=single,breaklines=true}}
#+LaTeX_HEADER: {}
#+LaTeX_HEADER: \newcommand{\hansl}[1]{\lstset{language={hansl},basicstyle={\ttfamily\small}}\lstinline{#1}}
# +LaTeX_HEADER: \lstset{backgroundcolor=\color{white},basicstyle=\ttfamily\footnotesize,breaklines=true, captionpos=b,commentstyle=\color{mygreen},escapeinside={\%*}{*)}, keywordstyle=\color{blue},stringstyle=\color{mymauve}, }
# +LaTeX_HEADER: \lstset{backgroundcolor=\color{lightgray!20},basicstyle=\ttfamily\footnotesize,breaklines=true, }
#+LaTeX_HEADER: \lstset{backgroundcolor=\color{lightgray!20}, }

#+name: setup-listings
#+begin_src emacs-lisp :exports none :results silent
  (setq org-latex-listings 'listings)
  (setq org-latex-custom-lang-environments
  	;'((emacs-lisp "common-lispcode")))
  	'((emacs-lisp "hansl-gretl")))
  (setq org-latex-listings-options
	'(("frame" "lines")
	  ("basicstyle" "\\scriptsize")
	  ("basicstyle" "\\ttfamily")
	  ("numbers=none" "left")
	  ("backgroundcolor=\\color{lightgray!20}")
	  ("numberstyle" "\\tiny")))
  (setq org-latex-to-pdf-process
	'("pdflatex -interaction nonstopmode -output-directory %o %f"
	"pdflatex -interaction nonstopmode -output-directory %o %f"
	"pdflatex -interaction nonstopmode -output-directory %o %f"))
  (org-add-link-type
   "latex" nil
   (lambda (path desc format)
     (cond
      ((eq format 'html)
       (format "<span class=\"%s\">%s</span>" path desc))
      ((eq format 'latex)
       (format "\\%s{%s}" path desc)))))
#+end_src

# \lstnewenvironment{code}
#     {\lstset{language=haskell,
#     basicstyle=\small\ttfamily,
#     numbers=left,
#     numberstyle=\tiny\color{gray},
#     backgroundcolor=\color{lightgray},
#     firstnumber=auto
#     }}
#     {}

#+bibliography: ref.bib

# +latex: \clearpage

#+LATEX: \clearpage

* Simulación del ejemplo del precio de las viviendas con tres regresores

| Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/BucleSimuladorEjPvivienda.inp][BucleSimuladorEjPvivienda.inp]] |

En este ejercicio con [[https://gretl.sourceforge.net/es.html][Gretl]] usaremos un bucle para generar muchas
veces datos simulados con los que realizar muchas regresiones MCO de
un mismo modelo y así observar el comportamiento del estimador MCO.

** Tareas

- Fijamos el tamaño muestral :: Simulamos series de datos de 500
  observaciones. Indicamos la opción =--preserve= para que Gretl
  mantenga en memoria el escalar que fija el tamaño muestral =TM=
#+name: Fijamos el tamaño muestral
#+begin_src hansl
scalar TM  = 500
nulldata --preserve TM
#+end_src

- Simulamos S y D :: Generamos dos variables que serán los regresores
  no constantes: =S= con distribución uniforme (35, 120); =D= con
  distribución Chi cuadrado con 5 grados de libertad que vamos a
  multiplicar por 3
#+name: Simulamos S y D
#+begin_src hansl 
series S = randgen(U, 35, 120)
series D = randgen(X, 5) * 3
#+end_src

- Parte sistemática :: La parte /sistemática/ del modelo es
  $\Vect[s]{y} = 100(\Vect{1}) + 3\Vect{s} - 130\Vect{D}$
#+name: Parte sistemática 
#+begin_src hansl 
series YS = 100 + 3*S - 130*D
#+end_src

- Esperanza y desviación típica de U :: En cada iteración generaremos
  una nueva perturbación =U= con media cero =mu=0= y desviación típica
  =sigma=100= (por tanto la longitud o norma de =U= será 100 en cada
  iteración)
#+name: Esperanza y desviación típica de U
#+begin_src hansl 
scalar mu    = 0
scalar sigma = 100
#+end_src

- Generación del vector de perturbaciones U :: 
#+name: Generación del vector de perturbaciones U
#+begin_src hansl 
series U = randgen(N, mu ,sigma )
#+end_src

- Comprobación de si U es ortogonal a los regresores S y D :: Dos
  vectores son perpendiculares si la media del producto Hadamard
  (componente a componente) entre ellos es nula. Si uno de los
  vectores tiene media nula, entonces ambos vectores son ortogonales
  si su correlación es nula. Vamos a calcular estos estadísticos
#+name: Comprobación de si U es ortogonal a los regresores S y D
#+begin_src hansl 
scalar mU  = mean(U)
scalar mUS = mean(U*S)
scalar mUD = mean(U*D)
scalar cUS = corr(U,S)
scalar cUD = corr(U,D)
#+end_src

- Parámetros beta estimados :: En cada iteración guardamos los betas
  estimados
#+name: Parámetros beta estimados
#+begin_src hansl
scalar b1 = $coeff(const)
scalar b2 = $coeff(S)
scalar b3 = $coeff(D)
#+end_src

- Visualización de resultados y guardado en disco :: Para estudiar los
  resultados, mostramos los estadísticos calculados y los guardamos en
  el fichero ~coef.gdt~.
#+name: Visualización de resultados y guardado en disco
#+begin_src hansl
print mU mUS mUD cUS cUD b1 b2 b3
store "@workdir/coef.gdt" mU mUS mUD cUS cUD b1 b2 b3
#+end_src

- Análisis gráfico de los resultados :: Una vez finalizado el bucle,
  pedimos a Gretl que abra el fichero de resultados guardado (se
  abrirá nueva sesión) y generamos unos diagramas donde vamos a ver
  cómo perturbaciones más alejadas de la perpendicularidad con los
  regresores afectan más a las estimaciones del parámetro beta
  asociado al regresor correspondiente.
#+name: Análisis gráfico de los resultados
#+begin_src hansl 
open "@workdir/coef.gdt"
MediaU_b1  <- gnuplot b1 mU  --output="display"
CorrUS_b2  <- gnuplot b2 cUS --output="display"
CorrUD_b3  <- gnuplot b3 cUD --output="display"
CorrUD_b2  <- gnuplot b2 cUD --output="display"
CorrUS_b3  <- gnuplot b3 cUS --output="display"
#+end_src

** Estructura del guión

#+begin_src hansl :noweb tangle :tangle ./pub/scripts/BucleSimuladorEjPvivienda.inp
<<Fijamos el tamaño muestral>>
<<Simulamos S y D>>
<<Parte sistemática>>
<<Esperanza y desviación típica de U>>
loop 5000 --progressive --quiet
     <<Generación del vector de perturbaciones U>>
     series Y  = YS + U
     <<Comprobación de si U es ortogonal a los regresores S y D>>
     ols Y 0 S D
     <<Parámetros beta estimados>>
     <<Visualización de resultados y guardado en disco>>
endloop
<<Análisis gráfico de los resultados>>
#+end_src

# +LATEX: \clearpage
#+latex: \noindent
*Código completo de la práctica* ~BucleSimuladorEjPvivienda.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/BucleSimuladorEjPvivienda.inp}
#+LATEX: \clearpage


* Simulación del ejemplo del precio de las viviendas con tres regresores que cambian

| Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/BucleSimuladorEjPvivienda2.inp][BucleSimuladorEjPvivienda2.inp]] |

En este ejercicio con [[https://gretl.sourceforge.net/es.html][Gretl]] repetimos lo anterior, pero en cada
iteración también cambian los regresores.

** Estructura del guión

#+begin_src hansl :noweb tangle :tangle ./pub/scripts/BucleSimuladorEjPvivienda2.inp
<<Fijamos el tamaño muestral>>
<<Esperanza y desviación típica de U>>
loop 5000 --progressive --quiet
     <<Simulamos S y D>>
     <<Parte sistemática>>
     <<Generación del vector de perturbaciones U>>
     series Y  = YS + U
     <<Comprobación de si U es ortogonal a los regresores S y D>>
     ols Y 0 S D
     <<Parámetros beta estimados>>
     <<Visualización de resultados y guardado en disco>>
endloop
<<Análisis gráfico de los resultados>>
#+end_src

# +LATEX: \clearpage
#+latex: \noindent
*Código completo de la práctica* ~BucleSimuladorEjPvivienda2.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/BucleSimuladorEjPvivienda2.inp}
#+LATEX: \clearpage


* Simulación del ejemplo del precio de las viviendas con tres regresores que cambian pero U se mantiene

| Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/BucleSimuladorEjPvivienda3.inp][BucleSimuladorEjPvivienda3.inp]] |

En este ejercicio con [[https://gretl.sourceforge.net/es.html][Gretl]] repetimos lo anterior, pero en cada
iteración solo cambian los regresores.

** Estructura del guión

#+begin_src hansl :noweb tangle :tangle ./pub/scripts/BucleSimuladorEjPvivienda3.inp
<<Fijamos el tamaño muestral>>
<<Esperanza y desviación típica de U>>
<<Generación del vector de perturbaciones U>>
loop 5000 --progressive --quiet
     <<Simulamos S y D>>
     <<Parte sistemática>>
     series Y  = YS + U
     <<Comprobación de si U es ortogonal a los regresores S y D>>
     ols Y 0 S D
     <<Parámetros beta estimados>>
     <<Visualización de resultados y guardado en disco>>
endloop
<<Análisis gráfico de los resultados>>
#+end_src

# +LATEX: \clearpage
#+latex: \noindent
*Código completo de la práctica* ~BucleSimuladorEjPvivienda3.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/BucleSimuladorEjPvivienda3.inp}
#+LATEX: \clearpage


* Simulación del ejemplo del precio de las viviendas con tres regresores ortogonales

| Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/BucleSimuladorEjPvivienda4.inp][BucleSimuladorEjPvivienda4.inp]] |

En este ejercicio con [[https://gretl.sourceforge.net/es.html][Gretl]] repetimos lo anterior, pero en cada
iteración cambia la perturbación y cambian los regresores, pero los
regresores son ortogonales entre si.

- Simulamos S y D ortogonales :: Generamos dos variables que serán los
  regresores no constantes: =S= con distribución uniforme (35, 120);
  =D= con distribución Chi cuadrado con 5 grados de libertad que vamos
  a multiplicar por 3; pero luego ortogonalizamos los regresores.
#+name: Simulamos S y D ortogonales
#+begin_src hansl 
series S0 = randgen(U, 35, 120)
series D0 = randgen(X, 5) * 3
ols S0 0
series S = $uhat
ols D0 0 S
series D = $uhat
#+end_src

** Estructura del guión

#+begin_src hansl :noweb tangle :tangle ./pub/scripts/BucleSimuladorEjPvivienda4.inp
<<Fijamos el tamaño muestral>>
<<Esperanza y desviación típica de U>>
loop 5000 --progressive --quiet
     <<Simulamos S y D ortogonales>>
     <<Parte sistemática>>
     <<Generación del vector de perturbaciones U>>
     series Y  = YS + U
     <<Comprobación de si U es ortogonal a los regresores S y D>>
     ols Y 0 S D
     <<Parámetros beta estimados>>
     <<Visualización de resultados y guardado en disco>>
endloop
<<Análisis gráfico de los resultados>>
#+end_src

#+LATEX: \clearpage
#+latex: \noindent
*Código completo de la práctica* ~BucleSimuladorEjPvivienda4.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/BucleSimuladorEjPvivienda4.inp}
#+LATEX: \clearpage


* Simulación del ejemplo del precio de las viviendas forzando a que la muestra de U cumpla los supuestos

| Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/BucleSimuladorEjPvivienda5.inp][BucleSimuladorEjPvivienda5.inp]] |

En este ejercicio con [[https://gretl.sourceforge.net/es.html][Gretl]] repetimos lo anterior, pero en cada
iteración también cambian los regresores.

- Generación del vector de perturbaciones U forzando que la muestra cumpla los supuestos ::
#+name: Generación del vector de perturbaciones U forzando que la muestra cumpla los supuestos
#+begin_src hansl
series U  = randgen(N, 0, 1)
series U  = U - mean(U)
series U  = U / sqrt( var(U)*(TM-1)/TM )
series U  = mu + sigma * U
ols U 0 S D
series U  = $uhat
#+end_src

** Estructura del guión

#+begin_src hansl :noweb tangle :tangle ./pub/scripts/BucleSimuladorEjPvivienda5.inp
<<Fijamos el tamaño muestral>>
<<Esperanza y desviación típica de U>>
loop 5000 --progressive --quiet
     <<Simulamos S y D>>
     <<Parte sistemática>>
     <<Generación del vector de perturbaciones U forzando que la muestra cumpla los supuestos>>
     series Y  = YS + U
     <<Comprobación de si U es ortogonal a los regresores S y D>>
     ols Y 0 S D
     <<Parámetros beta estimados>>
     <<Visualización de resultados y guardado en disco>>
endloop
<<Análisis gráfico de los resultados>>
#+end_src

#+LATEX: \clearpage
#+latex: \noindent
*Código completo de la práctica* ~BucleSimuladorEjPvivienda5.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/BucleSimuladorEjPvivienda5.inp}
#+LATEX: \clearpage


* Efectos del incumplimiento de algunos supuestos (perturbaciones sin esperanza nula)

| Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/BucleSimuladorEjPvivienda6.inp][BucleSimuladorEjPvivienda6.inp]] |

Vamos a ver cómo afecta a las estimaciones simular modelos que
incumplen algunos de los supuestos. Por ejemplo, ¿qué pasa si las
perturbaciones tienen esperanza no nula?

** Estructura del guión

#+begin_src hansl :noweb tangle :tangle ./pub/scripts/BucleSimuladorEjPvivienda6.inp
<<Fijamos el tamaño muestral>>
scalar mu    = 1000
scalar sigma = 100
loop 5000 --progressive --quiet
     <<Simulamos S y D>>
     <<Parte sistemática>>
     <<Generación del vector de perturbaciones U>>
     series Y  = YS + U
     <<Comprobación de si U es ortogonal a los regresores S y D>>
     ols Y 0 S D
     <<Parámetros beta estimados>>
     <<Visualización de resultados y guardado en disco>>
endloop
<<Análisis gráfico de los resultados>>
#+end_src

# +LATEX: \clearpage
#+latex: \noindent
*Código completo de la práctica* ~BucleSimuladorEjPvivienda6.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/BucleSimuladorEjPvivienda6.inp}
#+LATEX: \clearpage



** COMMENT Antiguo enunciado
- Modifique el guión ~BucleSimuladorEjPvivienda2.inp~ de la Práctica
  [[Simulación del ejemplo del precio de las viviendas con tres
  regresores que cambian]] para que genere modelos con perturbaciones
  que no tienen esperanza nula.

  + ¿Qué ocurre con los parámetros estimados? ¿Qué se ve más afectado
    las pendientes o la constante? Pruebe con distintos valores
    esperados (positivos, negativos y mayores o menores en valor
    absoluto).

  + La dispersión de las estimaciones ¿se ve también afectada?  ¿o
    sólo los valores medios?
    
  + Fuera del bucle, genere alguna simulación y observe el diagrama de
    dispersión entre los precios simulados y las superficies.

- Verifique que
  + Los residuos tienen media cero (pues la regresión tiene término constante)
  + Los residuos son perpendiculares a \textsf{S}
  + Los residuos son perpendiculares a \textsf{D}
  + No obstante, dado que los residuos tienen media cero (son
    variables centradas) la correlación mide el coseno del ángulo, así
    que la correlación entre los residuos y los regresores es cero.


* Efectos del incumplimiento de algunos supuestos (perturbaciones no ortogonales a S)

| Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/BucleSimuladorEjPvivienda7.inp][BucleSimuladorEjPvivienda7.inp]] |

Vamos a ver cómo afecta a las estimaciones simular modelos que
incumplen algunos de los supuestos. Por ejemplo, ¿qué pasa si las
perturbaciones no son ortogonales a uno o más regresores no
constantes?

- Definición de la matriz para generar correlación entre U y S :: Definimos
  la matriz con la que generar perturbaciones correladas con los
  regresores (/No recuerdo de donde saqué este modo de hacerlo/).
#+name: Definición de la matriz para generar correlación entre U y S
#+begin_src hansl
matrix C  = {1 ,   0,   0; 0 ,  1,   0; -10,  0,  1}
#matrix C  = {1 ,   0,   0; 0 ,  1,   0;  0, 100,  1}
#+end_src


- Generación del vector de perturbaciones U correladas con los regresores :: (/No
  recuerdo de donde saqué este modo de hacerlo/).
#+name: Generación del vector de perturbaciones U correladas con los regresores
#+begin_src hansl 
series U0 = randgen(N, 0, 1)
matrix Z = {S,D,U0}
Z *= C'               #  note: use the transpose '
series U  = Z[,3]     # generamos las perturbaciones
#+end_src


** Estructura del guión

#+begin_src hansl :noweb tangle :tangle ./pub/scripts/BucleSimuladorEjPvivienda7.inp
<<Fijamos el tamaño muestral>>
<<Esperanza y desviación típica de U>>
<<Definición de la matriz para generar correlación entre U y S>>
loop 5000 --progressive --quiet
     <<Simulamos S y D>>
     <<Parte sistemática>>
     <<Generación del vector de perturbaciones U correladas con los regresores>>
     series Y  = YS + U
     <<Comprobación de si U es ortogonal a los regresores S y D>>
     ols Y 0 S D
     <<Parámetros beta estimados>>
     <<Visualización de resultados y guardado en disco>>
endloop
<<Análisis gráfico de los resultados>>
#+end_src

#+LATEX: \clearpage
#+latex: \noindent
*Código completo de la práctica* ~BucleSimuladorEjPvivienda7.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/BucleSimuladorEjPvivienda7.inp}
#+LATEX: \clearpage


** COMMENT Antiguo enunciado


Vamos a ver cómo afecta a las estimaciones simular modelos que
incumplen algunos de los supuestos.

- El guión (que aparece más abajo) genera perturbaciones correladas
  con los regresores. Compruebe si en este caso es fiable la regresión
  MCO para obtener una estimación de los parámetros.
      
- Observe la matriz de correlaciones entre =U=, =D= y =S=.

- ¿Con quien presenta una elevada correlación la perturbación =U=?
  ¿Qué parámetro estimado se ve más afectado?
      

- Por último, fuera del bucle realice una proyección del precio sobre
  los regresores, pero excluyendo el término constante. Verifique que
      + Los residuos no tienen media cero
      + Los residuos son perpendiculares a =S=
      + Los residuos son perpendiculares a =D=
      + No obstante, dado que tanto los residuos como =S= y =D= no
        tienen media cero (no son variables centradas) la correlación
        no mide el coseno del ángulo, así que la correlación entre los
        residuos y los regresores no es cero.


* COMMENT NO sé

1) Simulamos series de datos de 500 observaciones
  
   + */~Archivo -> Nuevo conjunto de datos~/*, e indicamos el número
     de observaciones: 1500. Marcamos /de sección cruzada/ y
     continuamos adelante. Dejamos sin marcar ~empezar a introducir
     los valores de los datos~ y pulsamos ~Aceptar~.

   + o bien:
     #+begin_src hansl 
   nulldata 1500
     #+end_src

2) Generamos tres variables: =S= con distribución uniforme (35, 120);
   =D= con distribución Chi cuadrado con 5 grados de libertad que
   vamos a multiplicar por 3 y =U= con distribución Normal de media 0
   y desviación típica 40

   + */~Añadir -> Variable aleatoria~/* y se elige para cada
     variable el tipo de distribución, los valores de los parámetros y
     el nombre de la variable

   + o bien
     #+begin_src hansl 
   series S = randgen(U, 35, 120)
   series D = randgen(X, 5) * 3
   series U = randgen(N, 0, 40)
     #+end_src

3) Simulamos los precios según el modelo $\Vect{p} = 300\Vect{1} +
   5\Vect{s} - 2\Vect{d} + \Vect{u}$

   + */~Añadir -> Definir nueva variable~/* y tecleamos: ~P = 300 + 5*S - 2*D + U~

   + O bien 
     #+begin_src hansl
       series P = 300 + 5*S - 2*D + U
     #+end_src

4) Observe los estadísticos de las variables de modelo. En particular,
   ¿son ortogonales =S= y =D= respecto al regresor constante \Vect{1}?

   + */~Ver -> Estadísticos principales~/* con el ratón marcamos =D=,
     =S= y =P=.

   + O bien 
     #+begin_src hansl
       summary P S D
     #+end_src

5) El valor absoluto de la correlación entre =D= y =S= ¿es grande o
   pequeño?

   + */~Ver -> Matriz de correlación~/* y selecciones =D= y =S=.

   + O bien 
     #+begin_src hansl
       corr S D
     #+end_src

6) Observe los diagramas de dispersión de =P= con =S=, el de =P= con
   =D=, y el de los regresores =S= y =D=:

   + */~Ver -> Gráficos -> Gráfico X-Y (Scatter)~/*. Indicamos =S= como ~variable del eje x~. Indicamos =P= como ~variable del eje y~.

   + */~Ver -> Gráficos -> Gráfico X-Y (Scatter)~/*. Indicamos =D= como ~variable del eje x~. Indicamos =P= como ~variable del eje y~.

   + */~Ver -> Gráficos -> Gráfico X-Y (Scatter)~/*. Indicamos =S= como ~variable del eje x~. Indicamos =D= como ~variable del eje y~.

   + O bien 
     #+begin_src hansl
       scaterPS <- gnuplot P S
       scaterPD <- gnuplot P D
       scaterDS <- gnuplot D S
     #+end_src

     Nótese como dichos diagramas reflejan las correlaciones entre las distintas variables del modelo.

7) Ajuste por MCO =P= empleando =S= y =D=:

   + pinche en */~Modelo -> Mínimos Cuadrados Ordinarios~/* y selecciones =D= y =S=.

     - Elija =P= como regresando o "variable dependiente" (marque la opción ~Selección por defecto~).

     - Elija =S= y =D= como regresores o "Variables independientes". Pinche en ~Aceptar~.

     - En la ventana del modelo pinche en */~Archivo -> Guardar como icono y cerrar~/*.

     - Con el botón derecho del ratón, pinche sobre el icono del
       modelo estimado y seleccione ~Añadir a la tabla de modelos~.

   + O bien 
     #+begin_src hansl
       ModeloCompleto <- ols P 0 S D
       modeltab add
     #+end_src

   Observe que el ajuste recupera aproximadamente los valores de los
   parámetros del modelo simulado.

   Observe el /plano de regresión/: abra la ventana del modelo
   ajustado y pinche en */~Gráficos -> Gráfico de variable estimada y
   observada -> Contra S y D~/*

   
  
  - *Tarea adicional* Observe que el papel del parámetro $\beta_1$
    que acompaña al término constante es equilibrar los valores
    medios a ambos lados de la ecuación; es decir, asegurar que
    \[\media{\Vect{p}}=\Estmc{\beta_1}+\Estmc{\beta_2}\media{\Vect{s}}+\Estmc{\beta_3}\media{\Vect{d}}\]
    Verifique que efectivamente
    \[\Estmc{\beta_1}=\media{\Vect{p}}-\Estmc{\beta_2}\media{\Vect{s}}-\Estmc{\beta_3}\media{\Vect{d}}\]

    + Hágalo empleando una calculadora o indique el cálculo en el guión de Gretl con
      #+begin_src hansl	 
	## TAREA ADICIONAL ####
        AjusteMediasC = mean(P) - $coeff(S)*mean(S) - $coeff(D)*mean(D)
        beta1HatC     = $coeff(const)
	######################	 
      #+end_src

      /Otra manera de aludir a los betas estimados es generar una
      matriz columna con los betas: ~beta = $coeff~, de manera que
      ~beta[1,1]~, ~beta[2,1]~ y ~beta[3,1]~ son $\Estmc{\beta_1}$,
      $\Estmc{\beta_2}$ y $\Estmc{\beta_3}$ respectivamente./

** Omisión de regresores       
1) Si se omite el regresor =D= del ajuste ¿qué esperaría que ocurra
   con el parámetro asociado a la cte?

  + pinche en */~Modelo -> Mínimos Cuadrados Ordinarios~/*

    - En la lista de variables dependientes, pinche sobre =D= y pulse la flecha roja para eliminar dicha variable del
      modelo. Pinche en ~Aceptar~.

    - la ventana del modelo pinche en */~Archivo -> Guardar como icono y cerrar~/*.

    - añada este modelo a la ~Tabla de modelos~.

  + O bien 
    #+begin_src hansl
      ModeloSinD <- ols P 0 S
      modeltab add
    #+end_src

  ¿Confirman los resultados lo esperado respecto a los parámetros estimados?

  - *Tarea adicional* Recuerde que el papel del parámetro $\beta_1$
    que acompaña al término constante es equilibrar los valores
    medios a ambos lados de la ecuación; en este caso,
    \[\media{\Vect{p}}=\Estmc{\beta_1}+\Estmc{\beta_2}\media{\Vect{s}}\]
    Verifique que efectivamente
    \[\Estmc{\beta_1}=\media{\Vect{p}}-\Estmc{\beta_2}\media{\Vect{s}}\]

    + Hágalo empleando una calculadora o indique el cálculo en el guión de Gretl con
      #+begin_src hansl	 
        ## TAREA ADICIONAL ####
        AjusteMediasNoD = mean(P) - $coeff(S)*mean(S)
        beta1HatNoD = $coeff(const)
        ######################	 
      #+end_src
       
- Repita el experimento, pero esta vez incluyendo =D= y excluyendo =S=

  + pinche en */~Modelo -> Mínimos Cuadrados Ordinarios~/*

    - Elimine de la lista de regresores la variable =S=, e incluya =D= como regresor. Pinche en ~Aceptar~.

    - la ventana del modelo pinche en */~Archivo -> Guardar como icono y cerrar~/*.

    - añada este modelo a la ~Tabla de modelos~.

  + O bien 
    #+begin_src hansl
      ModeloSinS <- ols P 0 D
      modeltab add
    #+end_src
    donde ~modeltab show~ muestra la tabla de modelos ajustados.

  ¿Confirman los resultados lo esperado respecto a los parámetros estimados?

  + *Tarea adicional* Aquí $\beta_1$ asegura que
    \[\media{\Vect{p}}=\Estmc{\beta_1}+\Estmc{\beta_2}\media{\Vect{d}}\]
    Verifique que efectivamente
    \[\Estmc{\beta_1}=\media{\Vect{p}}-\Estmc{\beta_2}\media{\Vect{d}}\]

    + Hágalo empleando una calculadora o indique el cálculo en el guión de Gretl con
      #+begin_src hansl	 
	## TAREA ADICIONAL ####
        AjusteMediasNoS = mean(P) - $coeff(D)*mean(D)
        beta1HatNoD = $coeff(const)
	######################	 
      #+end_src

** Proyección omitiendo las constantes       
      
- ¿Y si calculamos la proyección ortogonal de los precios sobre =S=
  y =D= omitiendo la constante? ¿Qué espera que ocurra con los valores medios de =P=
  y del ajuste? Verifique su respuesta con el ordenador.

  + pinche en */~Modelo -> Mínimos Cuadrados Ordinarios~/*

    + Elija =S= y =D= como regresores, pero elimine la constante de la
      lista (/¡algo que jamás debe hacer en sus
      estimaciones!/). Pinche en ~Aceptar~.

    + la ventana del modelo pinche en */~Archivo -> Guardar como icono y cerrar~/*.

    + añada este modelo a la ~Tabla de modelos~.

  + O bien 
    #+begin_src hansl
      ModeloSin1 <- ols P S D
      modeltab add
    #+end_src

  ¿Confirman los resultados lo esperado respecto a los parámetros estimados?

  - *Tarea adicional* Aquí no hay un término constante, así que
    \[\media{\Vect{p}} \ne \Estmc{\beta_1}\media{\Vect{s}} + \Estmc{\beta_2}\media{\Vect{d}}\]
    El equilibro se da añadiendo la media de los errores (que por no
    existir término constante es distinta de cero).  Verifique que
    efectivamente
    \[\media{\Vect{p}} = \Estmc{\beta_1}\media{\Vect{s}} + \Estmc{\beta_2}\media{\Vect{d}} + \media{\res}\]

    + Hágalo empleando una calculadora o indique el cálculo en el guión de Gretl con
      #+begin_src hansl	 
       ## TAREA ADICIONAL ####
       MediaLadoIzdo = mean(P)
       MediaLadoDcho = $coeff(S)*mean(S) + $coeff(D)*mean(D) + mean($uhat)
       ######################	 
      #+end_src
      donde ~$uhat~ son los residuos de la  última regresión realizada.
 
    Este ajuste sin constante (*y que por tanto no debemos llamar
    /regresión MCO/*p) no logra equiparar correctamente los valores
    medios de ambos lados de la ecuación. Los únicos elementos
    disponibles para intentar dicho ajuste han sido los vectores de
    datos =S= y =D=, que tienen medias distintas de cero. Pero
    simultáneamente dichos vectores son necesarios para lograr el
    ajuste de las pendientes. Por ello los resultados al omitir la
    constante pueden ser desastrosos.
 
    # Es más, puesto que con cualquiera de los dos regresores es
    # posible de ajustar las medias (si se juega adecuadamente con los
    # betas), esta doble posibilidad se traduce en una mayor
    # incertidumbre en los valores estimados (¿qué variable es más
    # importante para ajustar la media?).

    # Observe en la tabla de modelos cómo han aumentado notablemente
    # las desviaciones típicas de los valores estimados en el modelo
    # sin término constante. Sin embargo, si se fija en los
    # coeficientes de determinación de dicha tabla de modelos, parece
    # que se ha logrado un mejor ajuste. El motivo es que, aunque
    # Gretl indique que calcula el coeficiente de determinación, no es
    # cierto. El programa Gretl realiza un cálculo alternativo cuando
    # el modelo carece de término constante.

    # Calcule los verdaderos coeficientes de determinación y
    # determinación ajustado. Hágalo tecleando las siguientes
    # instrucciones en la consola de Gretl
    # #+begin_src hansl	 
    # 	R2Sin1         = 1 - $ess/(($T-1) * var(P))
    #   R2AjustadoSin1 = 1 - ($T-1)/($T-2)*(1 - R2Sin1)
    # #+end_src

** ``Ortogonalizando'' los regresores no constantes respecto de las constantes
    
1) ¿Hay alguna forma de “ortogonalizar” =S= y =D= respecto de la
   constante?... ¡Si!, basta restar las medias (generar nuevos
   regresores en desviaciones respecto a su media):
   
  + */~Añadir -> Definir nueva variable~/* y escribimos ~series S0 =
    S - mean(S)~
  + */~Añadir -> Definir nueva variable~/* y escribimos ~series D0 =
    D - mean(D)~
  + O bien 
    #+begin_src hansl
      series S0 = S - mean(S)
      series D0 = D - mean(D)
    #+end_src

- Verifique que la media de =S0= y =D0= es cero. Ajuste por MCO los siguientes modelos:
  \[P = \beta_1 + \beta_2 S0 + \beta_3 D0\]
  y
  \[P = \beta_2 S0 + \beta_3 D0\]
  
  Compare los resultados entre ambos y con el modelo completo original.

  #+begin_src hansl
    ModeloCompEnDesviaciones <- ols P 0 S0 D0
    modeltab add
    ModeloEnDesviaciones <- ols P S0 D0
    modeltab add
    modeltab show
  #+end_src

  + Compare la estimación de $\beta_1$ del =ModeloCompEnDesviaciones=
    con la media de =P=.

  + ¿Se le ocurre alguna explicación para este resultado?

  + Observe en la tabla de modelos las similitudes del primer modelo
    en desviaciones con las obtenidas con el modelo completo
    original... ¡Todo es idéntico salvo la estimación de $\beta_1$!

  + Observe que aunque las pendientes estimadas toman los mismos
    valores en ambos modelos en desviaciones, la incertidumbre
    asociada en el caso del modelo en desviaciones sin contante es
    mucho mayor

#+latex: \vspace{10pt}
#+latex: \noindent
*Código completo de la práctica* ~SimuladorEjPvivienda.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/SimuladorEjPvivienda.inp}
#+LATEX: \clearpage

