#+title:  Lección 9
#+author: Marcos Bujosa
#+STARTUP: show4levels
#+LANGUAGE: es-es

#+EXPORT_FILE_NAME: pub/Lecc09

# +OPTIONS: toc:nil
#+OPTIONS: tags:nil

#+LATEX_CLASS: article

#+LATEX_HEADER: \usepackage[spanish]{babel}
#+LATEX_HEADER: \usepackage[margin=0.5in]{geometry}
#+LaTeX_HEADER: \usepackage[svgnames,x11names]{xcolor}
#+LaTeX_HEADER: \hypersetup{linktoc = all, colorlinks = true, urlcolor = DodgerBlue4, citecolor = PaleGreen1, linkcolor = SpringGreen4}
#+LaTeX_HEADER: \PassOptionsToPackage{hyphens}{url}
#+LaTeX_HEADER: \usepackage{nacal}

#+bibliography: ref.bib

#+LaTeX_HEADER: \usepackage{framed}

#+LaTeX_HEADER: \usepackage{listings}
#+LaTeX_HEADER: \input{hansl.tex}
#+LaTeX_HEADER: \lstnewenvironment{hansl-gretl}
#+LaTeX_HEADER: {\lstset{language={hansl},basicstyle={\ttfamily\footnotesize},numbers,rame=single,breaklines=true}}
#+LaTeX_HEADER: {}
#+LaTeX_HEADER: \newcommand{\hansl}[1]{\lstset{language={hansl},basicstyle={\ttfamily\small}}\lstinline{#1}}
# +LaTeX_HEADER: \lstset{backgroundcolor=\color{white},basicstyle=\ttfamily\footnotesize,breaklines=true, captionpos=b,commentstyle=\color{mygreen},escapeinside={\%*}{*)}, keywordstyle=\color{blue},stringstyle=\color{mymauve}, }
# +LaTeX_HEADER: \lstset{backgroundcolor=\color{lightgray!20},basicstyle=\ttfamily\footnotesize,breaklines=true, }
#+LaTeX_HEADER: \lstset{backgroundcolor=\color{lightgray!20}, }

#+name: setup-listings
#+begin_src emacs-lisp :exports none :results silent
  (setq org-latex-listings 'listings)
  (setq org-latex-custom-lang-environments
  	;'((emacs-lisp "common-lispcode")))
  	'((emacs-lisp "hansl-gretl")))
  (setq org-latex-listings-options
	'(("frame" "lines")
	  ("basicstyle" "\\scriptsize")
	  ("basicstyle" "\\ttfamily")
	  ("numbers=none" "left")
	  ("backgroundcolor=\\color{lightgray!20}")
	  ("numberstyle" "\\tiny")))
  (setq org-latex-to-pdf-process
	'("pdflatex -interaction nonstopmode -output-directory %o %f"
	"pdflatex -interaction nonstopmode -output-directory %o %f"
	"pdflatex -interaction nonstopmode -output-directory %o %f"))
  (org-add-link-type
   "latex" nil
   (lambda (path desc format)
     (cond
      ((eq format 'html)
       (format "<span class=\"%s\">%s</span>" path desc))
      ((eq format 'latex)
       (format "\\%s{%s}" path desc)))))
#+end_src


# \lstnewenvironment{code}
#     {\lstset{language=haskell,
#     basicstyle=\small\ttfamily,
#     numbers=left,
#     numberstyle=\tiny\color{gray},
#     backgroundcolor=\color{lightgray},
#     firstnumber=auto
#     }}
#     {}

#+bibliography: ref.bib

# +latex: \clearpage

#+LATEX: \clearpage

* Estimación restringida vía mínimos cuadrados restringidos y vía sustitución
   :PROPERTIES:
   :header-args: :tangle ./pub/scripts/GujaratiEx8-3.inp
   :END:

| Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/GujaratiEx8-3.inp][GujaratiEx8-3.inp]] |

Cargue los datos ~Table_8.8.gdt~ de la pestaña del libro de Gujarati.
#+begin_src hansl 
open Table_8.8.gdt
#+end_src

- Estimación restringida :: Suponga que deseamos estimar el siguiente
  modelo en logaritmos proveniente de una función de Cobb-Douglas:
  \begin{displaymath}
     \ln \VA{Y} = 
     \beta_1\VAindUno + \beta_2\ln\VA{k} + \beta_3\ln\VA{L} + \per;
  \end{displaymath}
  pero que deseamos imponer la restricción de rendimientos constantes a
  escala, es decir, $\beta_2+\beta_3=1$. Veamos dos maneras equivalentes
  de proceder:
  
  1) Transforme las variables en logaritmos
    #+begin_src hansl 
     logs GDP Employ Capital
    #+end_src
    + Estime por MCO el modelo sin restringir (guarde el el modelo como
      icono con el nombre =U= (unrestricted).
      #+begin_src hansl 
       # modelo 1
       U <- ols l_GDP const l_Employ l_Capital
      #+end_src
    + Imponga la restricción $\beta_2+\beta_3=1$. Desde la ventana del
      modelo estimado sin restricciones siga los pasos */~Contrastes ->
      Restricciones lineales~/* y teclee =b[2]+b[3]=1= o bien, en un
      guión o la consola teclee
      #+begin_src hansl 
       restrict
        b[2]+b[3]=1
       end restrict
      #+end_src
      Observe los coeficientes estimados resultantes tras imponer la
      restricción.
      
  2) Defina las variables \textsf{Capital/Employ} y \textsf{GDP/Employ}
     y transforme las nuevas variables mediante logaritmos.
    #+begin_src hansl 
     series CE   = Capital/Employ
     series GDPE = GDP/Employ
     logs CE GDPE
    #+end_src
    + Estime por MCO el modelo
      \begin{displaymath}
         \ln \VA{Y} = \beta_1\VAindUno + \beta_2 \ln\frac{\VA{k}}{\VA{L}} + \per
      \end{displaymath}
      y compare los resultados anteriores (los del primer modelo tras
      imponer la restricción).
      #+begin_src hansl 
       # modelo 2
       R <- ols l_GDPE const l_CE
      #+end_src
      
- Contraste de la hipótesis :: Calcule el estadístico $\Festadistico$
  (en su formulación mediante sumas residuales de los modelos
  restringidos y sin restringir) y su /p/-valor para contrastar la
  hipótesis de rendimientos constantes a escala. ¿Rechaza la \Hnula al
  5% de significación?
  #+begin_src hansl 
   /* contraste de la F mediante sumas residuales */
   scalar r = 1                             # num. restriciones (solo una en este caso)
   scalar f = U.$df*(R.$ess-U.$ess)/U.$ess/r
   pvalue F r U.$df f
  #+end_src

#+LATEX: \clearpage
#+latex: \vspace{10pt}
#+latex: \noindent
** Código completo de la práctica ~GujaratiEx8-3.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/GujaratiEx8-3.inp}
#+LATEX: \clearpage


* Test de Chow de cambio estructural
   :PROPERTIES:
   :header-args: :tangle ./pub/scripts/GujaratiSec8-8.inp
   :END:

| Guión: | [[https://github.com/mbujosab/Ectr/tree/master/Practicas/Gretl/scripts/GujaratiSec8-8.inp][GujaratiSec8-8.inp]] |

Cargue los datos ~Table_8.9.gdt~ de la pestaña del libro de Gujarati
con datos para la economía americana del 1970 a 1995.
#+begin_src hansl 
open Table_8.9.gdt
#+end_src

Considere el modelo:
\begin{displaymath}
  \VA{Y} = \beta_1\VAindUno + \beta_2\VA{X} + \per,
\end{displaymath}
donde \VA{X} es el ahorro de las familias e \VA{Y} es la renta
disponible.

En el año 1982 se produjo una importante crisis económica. Contraste
si el modelo es idéntico para toda la muestra, o si se produjo un
cambio estructural (use los periodos 1970--1981 y 1982--1995).

+ Estime el modelo restringido (mismos betas para todo el
  periodo). Guarde la Suma de los Residuos al Cuadrado (SRC)
  #+begin_src hansl 
   ModeloR       <- ols SAVINGS 0 INCOME --quiet
   scalar sse_R  = $ess
  #+end_src

+ Estime dos modelos, uno para los 12 primeros datos y otro para los
  14 siguientes. Guarde la Suma de los Residuos al Cuadrado (SRC)
  conjunta del modelo sin restringir.
  #+begin_src hansl 
   smpl 1 12
   ModeloU1      <- ols SAVINGS 0 INCOME --quiet
   scalar sse_U1  = $ess

   smpl full
   smpl 13 26
   ModeloU2      <- ols SAVINGS 0 INCOME --quiet
   scalar sse_U2  = $ess
  #+end_src

+ Calcule el estadístico del contraste de cambio estructural de Chow y
  su p-valor.
  #+begin_src hansl 
   scalar sse_U = sse_U1+sse_U2
   smpl full
   scalar chowtest = ((sse_R-sse_U)/2)/(sse_U/($nobs-4))
   pvalue F 2 $nobs-4 chowtest
  #+end_src

+ ¿Rechaza que el modelo es el mismo para todo el periodo? ¿o no?
  

#+LATEX: \clearpage
#+latex: \vspace{10pt}
#+latex: \noindent
** Código completo de la práctica ~GujaratiSec8-8.inp~
#+latex: \vspace{10pt}
\lstinputlisting{scripts/GujaratiSec8-8.inp}
#+LATEX: \clearpage
