name: econometria-aplicada
channels:
  - conda-forge
dependencies:
  - python=3.10
  - jupyter
  - matplotlib
  - texlive-core
  - pip
  - pip:
    - dataframe-image
    - numpy
    - sympy
    - pandas
    - matplotlib
    - seaborn
    - dataframe_image
    - statsmodels